### ISSUE TITLE
Evaluate ZEP SOAP API

### ISSUE THREAD

**Issue by b0x1** [Gepardec/mega#1]
Live Coding @ August 9th

- [x] Access as testuser
- [x] Define properties for  "active user"
- [x] ? Zeiten freigeben
- [x] Rechte
- [x] Monatsauswertung
  - [x] Pausen
  - [x] 10h
  - [x] Reisen
  - [x] Fehlerauswertung
  - [x] abnormale Einträge (kein Eintrag, zu wenig Stunden)

TODO: upload wsdl

**Comment by Ruhsi** [comment]
Definition von "active user" laut @WernerGepardec laut #11:
**Aktiver MA: Beschäftigungszeitraum ist laufend.**

**Comment by Ruhsi** [comment]
Bei der ZEP-Api kann bei der Methode:
`UpdateMitarbeiterResponseType updateMitarbeiter(UpdateMitarbeiterRequestType updateMitarbeiterRequest)`
ein neues Freigabedatum gesetzt werden. Dadurch wird das Freigabedatum des Mitarbeiters aktualisiert.

**Comment by Ruhsi** [comment]
In ZEP sind die Rechte Integerwerte:

- User -> 0
- Admin -> 1
- Controller -> 2

**Comment by WernerGepardec** [comment]
Liefert die ZEP API eine Fehlerliste? Etwa wenn Pausenzeiten nicht eingehalten werden, die Reise nicht korrekt verbucht ist, ...

**Comment by Ruhsi** [comment]
![projektzeiten](https://user-images.githubusercontent.com/24733670/65504720-e0a0bf00-dec7-11e9-95ed-45ccf1b3dd17.png)

Bei der API werden lediglich die Werte dargestellt. Eine Überprüfung von Fehlern oder eine gesamte Fehlerliste bekommt man nicht.

**Comment by Ruhsi** [comment]
Nicht vorhandene Einträge und 10h Einträge werden auch nicht überprüft.
Die Logik dazu muss selbst implementiert werden.
