### ISSUE TITLE
Dashboard link is not correct

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#107]
The following link should be used:

https://docs.google.com/spreadsheets/d/1wUJHMtkY47RhLIGytg_MXVe_hgPAj_yzozLMcv5hrdU/

**Comment by WernerGepardec** [comment]
@JulianGartner when is the bug fixed in prod?

**Comment by JulianGartner** [comment]
New deployment is now live in test-env!
After successful bugfix-review check with me so we can release to prod.

**Comment by cchet** [comment]
Already done
