### ISSUE TITLE
Show active employees

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#11]
Als OM möchte ich alle aktiv beschäftigte Benutzer im Dashboard sehen.

Akzeptanzkriterien:
 - Mitarbeiter ist angemeldet.
 - Mitarbeiterrolle aus ZEP auslesen und überprüfen, dass der Benutzer das Controlling-Recht, oder eine höheres Benutzerrecht hat.
 - Wenn der MA nicht die notwendigen Rechte hat, sollen keine anderen Benutzer angezeigt werden.
 - Aktiv beschäftigten MA werden in Tabellenform dargestellt. UI ist mit @kwimmergit abzustimmen.

Definition:
- Aktiver MA: Beschäftigungszeitraum ist laufend.

**Comment by cchet** [comment]
Already done
