### ISSUE TITLE
As an employee I want to see the current EMC1 status and comments of OM/PM (of the billing month), so that I know if I have tasks to do.

### ISSUE THREAD

**Issue by sthausmann** [Gepardec/mega#116]
AC:
- [x] only active employees are to be considered
  - activity status can be read from ZEP
  - Do not show employee after month in which he had his last day at work
  - Do not show employee before month in which he has his first day at work
- [x] the earliest month is the month where the ZEP release date is not set and also the status is not "fertig"
- [x] the approved employee-UX Design is used

**Comment by WernerBruckmueller** [comment]
UI Design: https://docs.google.com/document/d/1oFnqD38FHia5SWCXejC7faO4aMTcLsJtYchSkS6OAZQ/edit

**Comment by WernerBruckmueller** [comment]
Unfinished comments must always be visible.
All comments of a specific month must be visible in the same month (finished and unfinished).
