### ISSUE TITLE
As an employee I want to have a button to set EMC1 to done in the MEGA Dash, so that I do not have to use the excel document any more.

### ISSUE THREAD

**Issue by sthausmann** [Gepardec/mega#117]
- [ ]  check the duration of employment for the minimum and max month
- [ ]  the earliest month is the month where the ZEP release date is not set and also the status is not "fertig"
- [ ]  the current EMC1 status is shown in the MEGA dashboard (see #116 )
- [ ]  the status is persisted for the employee in the selected month
- [ ]  only a status change from "Offen" to "Fertig" is possible

**Comment by WernerBruckmueller** [comment]
Update: According to Evelyn the status "in Arbeit" is also necessary. 
AC:
- The following status changes are possible in this US:
 -- "offen" to "in Arbeit"
 -- "in Arbeit" to "Fertig"
 -- "offen" to "Fertig"
