### ISSUE TITLE
Display "Freigabe Datum" in dashboard

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#13]
As an OM I want to see the date up to which he froze his accounting for each employee.

**Comment by Ruhsi** [comment]
Die Mitarbeiter werden als Pagination in einer Gridlist und Tablelist angezeigt. Es kann zwischen den beiden Ansichten gewechselt werden. Das letzte Freigabedatum der Mitarbeiter wird in beiden Ansichten angezeigt.
Das Design muss noch mit @kwimmergit abgesprochen werden.

![13-Gridlist](https://user-images.githubusercontent.com/24733670/63741687-59dfce80-c896-11e9-987f-1f695b58bd55.png)
![13-Tablelist](https://user-images.githubusercontent.com/24733670/63741688-5a786500-c896-11e9-97b8-d8a4041aefd9.png)

**Comment by cchet** [comment]
Already done
