### ISSUE TITLE
Show monthly Report from a month

### ISSUE THREAD

**Issue by WernerGepardec** [Gepardec/mega#14]
As a MA I want to see the montly report from ZEP (System check). The MA want an overview of the known issues from the month after the last "Freigabe"-date.

"Monatsendauswertung"-Link: https://www.zep-online.de/zepgepardecservices/view/index.php?menu=MeineAuswertungenVerwaltungMgr&mgr=MeinZEPMitarbeiterMonatsendeMgr

Report should display the following system checks:
- month and year of the report
- "Freigabe Datum" from the current user
- "Pausenregelung" (see "Monatsendauswertung" in ZEP e.g.: 10-hours day (except travel days), working hours, minimum break of 30min after a >6hour day)
   > "nicht eingehaltene Pausenregelung" --> display Date, Type of Error
![image](https://user-images.githubusercontent.com/16414159/68749458-8cc87180-05fe-11ea-88dc-2a03857f5c54.png)
![image](https://user-images.githubusercontent.com/16414159/68862036-063e8d80-06ed-11ea-81d5-48eb78fafbc4.png)

- "Reisezeiten"-Check as in ZEP. E.g. from ZEP with wrong travel entry
![image](https://user-images.githubusercontent.com/16414159/68749384-6aceef00-05fe-11ea-8ba2-e950684c899c.png)

- Are all entries between 6 AM and 10 PM ? check "Gleitzeitrahmen". Errortext: "Gleitzeitrahmen wurde nicht eingehalten."

 If no issues are found, the display that no automatically issues are found.

The month after the "Freigabe Day" is shown. The month should not be changed by the user.
Display the linkt to the Monatsende-Google-Sheet
Precondition
The user must be logged in MEGA Dash and can only see his own data.

DoD

- [x] UI is approved by UX-Designer
- [x] Every user can see the dashboard from the current month
- [x] Every user sees the systemchecks
- [x] Automated frontend tests
- [x] Automated backend tests
- [x] The link to the Monatsende-Google-Sheet is shown

**Comment by WernerGepardec** [comment]
The "Kostenabrechnung" is not necessary, because the issues can be found with "Reisezeiten"

**Comment by mbrandm** [comment]
backend-logic and tests implemented
