### ISSUE TITLE
As the team we want to have a design draft for the "employee overview", so that we can create the HTML templates for this view.

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#156]
AC:
- [x] the draft is discussed with the PO
- [x] the design should contain: 
         - read only (for one employee): OMC1, OMC2, PMC1 --> ok, because better idea came up
         - editable: EMC1 --> ok
         - multiple projects should be handled in this view (e.g. a PM can have multiple projects and users) - discuss details with the PO before starting the draft (maybe not with MEGA 2.0) --> ok because not necessary
- [x] filter the states (check with #147) --> not necessary

**Comment by WernerBruckmueller** [comment]
Design is ok for me.
@rfischerGep ok for you?

**Comment by rfischerGep** [comment]
it's ok for me too
