### ISSUE TITLE
As any user I want to see the current version somewhere on the dashboard, so that I can alyways tell which version I am working with

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#168]
As any user I want to see the version of MEGA to know which version is currently deployed and can check which issues are part of this version.

AC
- The version is shown in the dashboard
- unique continuous number (e.g. in combination with the date?)

**Comment by cchet** [comment]
The version has been added to the `/config` rest response.
The following examples shows how it looks like during development.
```
{
    "version": "2.0.0.RC2-SNAPSHOT",
    "scope": "openid profile email",
    "clientId": "60018822787-4nlv6e1tit3q8ssfbe2e013790p939dt.apps.googleusercontent.com",
    "issuer": "https://accounts.google.com"
}
``` 

The following examples shows how it looks like when deployed in a stage.
``` 
{
    "scope": "openid profile email",
    "version": "FEATURE-168",
    "clientId": "60018822787-361in5i8h2kaqfmj7ue0ocn5s4acf5ci.apps.googleusercontent.com",
    "issuer": "https://accounts.google.com"
}
``` 

Additionally a new rest resource `/info` has been implemented which provides more details of the application.
The following examples shows how it looks like during development.
``` 
{
    "version": "2.0.0.RC2-SNAPSHOT",
    "branch": "local",
    "commit": "local",
    "buildDate": "06.09.2020 08:13",
    "buildNumber": 0
    "upTime": "0d 0h 1m 53s",
    "startedAt": "06.09.2020 10:13"
}
``` 
The following examples shows how it looks like when deployed in a stage.
``` 
{
    "branch": "feature/168",
    "version": "FEATURE-168",
    "commit": "f96999a3f3da851b9657a713d938911d06957dc9",
    "buildDate": "06.09.2020 08:33",
    "buildNumber": 2,
    "upTime": "0d 0h 4m 23s",
    "startedAt": "06.09.2020 10:43"
}
``` 

@Ollitod  @marioaslan 
Please integrate at least the version in the GUI which is provided by the `/config` rest response.
The application info can wait for now. If you have time implement it as well.
The application info should displayed in a dialog which could be opened via button in the menu where you the logout button resides.  

The branch is `feature/168`

@WernerBruckmueller  fyi

**Comment by sthausmann** [comment]
auf der TEST Getestet und für gut befunden
