### ISSUE TITLE
As employee I want to see and handle the comments in the employee-view.

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#186]
AC:
- [x] the approved UI Design für the employee interfaces is used
- [x] the employee can set a comment to done. The creator of the comment gets notified.
- [x] the employee is not able to undo a comment.
- [x] all comments of the current monthly period are shown
- [x] all open comments (including those from other months) are shown (maybe there are still open tasks from the month before)
- [x] a comment must include the name of the creator, creation date & time and text
- [x] if all comments are marked as done, the screen with the text "Die Kontrolle der Zeiten ist im Gange" is shown

**Comment by WernerBruckmueller** [comment]
@Ruhsi @rainer-gepardec how can I test the notifications?

**Comment by Ruhsi** [comment]
@WernerBruckmueller The mock for mailer is disabled in dev-stage. So the creator should get a notification
