### ISSUE TITLE
As PM I only want to handle the non-internal projects in MEGA

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#189]

**Comment by WernerBruckmueller** [comment]
AC:
- [ ] non internal projects should not be considered in the PM view (Filter: "Projektkategorie")

Note:
- [ ] non internal projects should also be checked in the employee view (e.g. checks in the first of the month)

**Comment by WernerBruckmueller** [comment]
@Ruhsi please create new stepentries. Now I'm PL of internal projects.

**Comment by WernerBruckmueller** [comment]
@Ruhsi @gattma 
Bug: I see the internal projects

**Comment by Ruhsi** [comment]
@WernerBruckmueller Can you send me a pic of your internals times from zep. I need to check the filter Rainer implementend
