### ISSUE TITLE
Adapt mail: Friendly Reminder

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#202]
Add a new list item to the mail notifications.

EMPLOYEE_CHECK_PROJECTTIME: For the employee reminder (only for MEGA 1.0, not for MEGA 2.0):
- Status im Monatsende-Dashboard(Link from config) aktualisieren  

OM_CONTROL_EMPLOYEES_CONTENT: For the OM reminder on the 3rd working day (only for MEGA 1.0, not for MEGA 2.0):
- Status im Monatsende-Dashboard(Link from config) aktualisieren 

OM_RELEASE: For the OM reminder on the 6th working day (only for MEGA 1.0, not for MEGA 2.0):
- Status im Monatsende-Dashboard(Link from config) aktualisieren 

OM_ADMINISTRATIVE: For the OM reminder on the 15th working day (with MEGA 1.0 and following Versions):
- Status im Monatsende-Dashboard(Link from config) aktualisieren 

PL_PROJECT_CONTROLLING: For the PM reminder (with MEGA 1.0 and following Versions):
- Status im Monatsende-Dashboard(Link from config) aktualisieren 

OM_SALARY: 
For the OM reminder (with MEGA 1.0 and following Versions):
- Status im Monatsende-Dashboard(Link from config) aktualisieren 

As soon as MEGA 2.0 is released to the public, these lines have to be removed again

**Comment by cchet** [comment]
@WernerBruckmueller  
To what dashboard we are supposed to link, the excel or mega?

**Comment by WernerBruckmueller** [comment]
@cchet to the excel
