### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by cchet** [Gepardec/mega#208]
- [x]  Delete the databases for 'test' and 'prod' because the have differed
- [x]  Switch stage for triggered backups to 'prod', they are on dev for testing 
- [x]  Tag a new version for related mega-infrastructure repository
- [x]  Add a documentation about which mega-infrastructure version needs to be used for this version and following hot fixes
- [x]  Ensure all test related rest endpoints are deleted from the source @rainer-gepardec 
- [x]  Check the trigger cron expressions

**Comment by sthausmann** [comment]
Due on 21.01.21

**Comment by cchet** [comment]
Database backups don't work because mega-* openshift projects are not joined. ItAndTel support has been notified
