### ISSUE TITLE
Combined checks of Times and Travel (with location) entries

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#212]
If there is a entry with a different "Arbeitsort" between a journey, an error is shown in "Kostenabrechnung" but not in MEGA.

How to reproduce this error:
Add traveling entry e.g.: Linz --> Wien
Add working entry with Arbeitsort "Wien"
Add working entry with your own working location ("erste Tätigkeitsstätte")
Add traveling entry Wien --> Linz

Error is shown in Kostenabrechnung: 	Die Reise endet 03.11.2020 11:30 Uhr, weil die nächste Buchung auf die erste Tätigkeitsstätte erfolgte, aber es fehlt eine Rückreise.

**Comment by cchet** [comment]
@WernerBruckmueller  
This is an enhancement, not a bug. 
This was never implemented.

**Comment by cchet** [comment]
Here we have now specified test scenarios https://github.com/Gepardec/mega/wiki/Tests but we need to refactor the checks of the project times, so this is maybe not event meant to be released in Mega 2.0.

The combination of times, travel with location needs to be implemented and existing code needs to be refactored.

**Comment by WernerBruckmueller** [comment]
@cchet Typo: "Abreitsort" --> "Arbeitsort"

**Comment by WernerBruckmueller** [comment]
@cchet 
Test failed:

8-10 reise nach wien
10-11 arbeit (Arbeitsstätte A)
12-13 rückreise linz

15-16 arbeit (erste Arbeitsstätte) <-- wird als fehler erkannt, ist aber ok

**Comment by cchet** [comment]
@WernerBruckmueller 

Unit Test sind erfolgreich für folgende Daten:

journeyTimeEntryFor(8, 10, JourneyDirection.TO, WorkingLocation.A);
projectTimeEntryFor(10, 11, WorkingLocation.A);
journeyTimeEntryFor(12, 13, JourneyDirection.BACK, WorkingLocation.A);

**Comment by WernerBruckmueller** [comment]
Was passiert wenn das noch hinzugefügt wird?
projectTimeEntryFor(14, 15, WorkingLocation.FIRST); 

Sollte auch möglich sein

**Comment by cchet** [comment]
@WernerBruckmueller 

BACK journey muss MAIN haben, denn wir kehren zur Hauptarbeitsstätte zurück.

12, 13, JourneyDirection.BACK, WorkingLocation.MAIN // geht
12, 13, JourneyDirection.BACK, WorkingLocation.A       // geht nicht, denn wir sind nach A zurückgekehrt und können jetzt nicht auf MAIN buchen
