### ISSUE TITLE
Add check for "Gleitzeitrahmen"

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#223]
As an employee I want to get a warning when my bookings (except travel time) is not in the "Gleitzeitrahmen".

See wiki: Kontrolle des Gleitzeitrahmens (06:00 bis 22:00 Uhr) , bei Buchungen außerhalb des Gleitzeitrahmens bitte um Rücksprache mit Evelyn/GF

**Comment by cchet** [comment]
Duplicates #237
