### ISSUE TITLE
Validate "Regelarbeitszeit"

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#237]
Quote from Wiki:
"Kontrolle des Gleitzeitrahmens (06:00 bis 22:00 Uhr) , bei Buchungen außerhalb des Gleitzeitrahmens bitte um Rücksprache mit Evelyn/GF  "

Note:
Passive travel time can be outside of this time limit. Except active travel time.

**Comment by cchet** [comment]
@Ruhsi   @gattma  @WernerBruckmueller 
Wie bei Journey Warnings wird jetzt auch ein warnings array mitgegeben, dass Meldungen enthält (Regelarbeitszeit ...).
Jetzt ist es eine Tabelle mit 3 Zeitfehlern, jetzt müssen auch unsere Meldung rein.

Redet euch da mit Werner zusammen, wie das ausschauen soll. 

Branch ist **feature/237-regelarbeitszeit-rule**

**Comment by WernerBruckmueller** [comment]
Passive Reisezeit darf auch außerhalb dieser Zeit sein (Passiv: Zug + KFZ passiv)

**Comment by cchet** [comment]
@Ruhsi  @gattma   
Ich bin da dran, sollte sich ausgehen.

@WernerBruckmueller 
Die Fahrzeuge müssen auf allen Umgebungen dieselbe id haben, ansonsten funktioniert es in der Prod nicht genau so wie die Arbeitsorte.

**Comment by cchet** [comment]
@WernerBruckmueller 
Siehe https://github.com/Gepardec/mega/wiki/Definitionen wegen den attributen und deren Werten.

**Comment by cchet** [comment]
@WernerBruckmueller 
Feature is implemented and builds. When done we can deploy the feature to the dev stage.

**Comment by WernerBruckmueller** [comment]
@cchet danke für die info. da es ein clone der prod ZEP Umgebung ist, sollte es passen.
Bitte um Info wenn es deployed ist, dann teste ich es.
