### ISSUE TITLE
See projects which are not set to done

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#242]
As employee and I want to see which projects are not set to done.

Possible (quick?) solutions:
As Text or Mouse over

**Comment by WernerBruckmueller** [comment]
Bei Stefan habe ich alle seine Projekte (im selben Monat) auf erledigt gesetzt, jedoch ist PM Check anscheinend noch rot.

**Comment by Ruhsi** [comment]
Should we restrict it to only external projects? Now internal and external OM stepentries and all project-lead stepentries are used
