### ISSUE TITLE
PM view should not be visible

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#249]
Als User darf ich die PM view nicht sehen.
Der USer hat nur die User ZEP Berechtigung.

**Comment by Ruhsi** [comment]
@WernerBruckmueller die Rollen in ZEP haben keine Relevanz mehr. OM ist bei uns hartkodiert Evelyn eingetragen und als PM gilt jeder der in irgendeinem Projekt in diesem Monat PL ist

**Comment by WernerBruckmueller** [comment]
@Ruhsi wenn man sich als "normaler" user anmeldet, hat man die PM view gesehen, ohne dass der User ein PM war.

**Comment by Ruhsi** [comment]
@WernerBruckmueller kannst du uns sagen mit welchem Benutzer du das probiert hast? Und in welchem Monat..

**Comment by Ruhsi** [comment]
@WernerBruckmueller da haben letztens die Daten auf der test nicht ganz gestimmt. Stefan sieht wieder nur 'Mein Mega'.
Ich habe damals zu Testzwecken stepentries für Stefan hartkodiert in die DB eingefügt, die mit ZEP nicht zusammengepasst haben.
