### ISSUE TITLE
error in OM view

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#251]
Error:
Ein Fehler ist aufgetreten: InvalidPipeArgument: 'Unable to convert "NULL" into a date' for pipe 'kl'

**Comment by Ruhsi** [comment]
Bei Manuel Vilim ist nach dem Syncen kein Freigabedatum in der DB eingetragen.
@WernerBruckmueller wie sollen wir das Handeln wenn ein Mitarbeiter in ZEP kein Freigabedatum eingetragen hat, weil er zb gerade neu angefangen hat? Sollen wir das letzte Monat annehmen?

**Comment by WernerBruckmueller** [comment]
Für die OM View soll es unerheblich sein. Das ist vorher auch schon gegangen. ich glaube da ist dann einfach NULL dortgestanden.
