### ISSUE TITLE
Comment: Link should be clickable in employee view

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#267]
Kommentar darf nur über Checkbox abgehakt werden.
Link soll auch anklickbar sein.

**Comment by cchet** [comment]
@WernerBruckmueller   @Ruhsi 
Is this done and merged, or still open?

**Comment by cchet** [comment]
Ok, I saw Milestone 2.0.1, so I think this is not for this release?
If no, then please move the ticket to the backlog.

**Comment by WernerBruckmueller** [comment]
done

**Comment by Ruhsi** [comment]
@WernerBruckmueller what means done? Is it working on test?

**Comment by WernerBruckmueller** [comment]
done means in this context, that I moved it back to the backlog. 
Have you started or finished the implementation? When yes please contact me in hangouts

**Comment by WernerBruckmueller** [comment]
@cchet is already fixed and tested in release 3
