### ISSUE TITLE
Support for travels over multiple days

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#274]
We want the support of detecting travels which span over multiple days.

![image](https://user-images.githubusercontent.com/16414159/104735691-33982880-5742-11eb-86d5-f9138f395315.png)

**Comment by WernerBruckmueller** [comment]
@cchet warum soll das ein enhancement sein? Das hat bei MEGA 1.0 funktioniert.
Bitte auch mit mir rücksprechen.

**Comment by WernerBruckmueller** [comment]
Beispiel auch in Prod bei Werner am 5. märz

**Comment by WernerBruckmueller** [comment]
see also #309

**Comment by Ruhsi** [comment]
@WernerBruckmueller @ArminGepardec die Hinreise kann ja auch zb. 10 Tage vorher gemacht das heißt wir müssen das gesamte Monat zurückschauen ob da eine Hinreise stattgefunden hat. Und was noch blöder ist, wenn die Hinreise im Vormonat stattgefunden hat. zb Hinreise 29.4. Rückreise 3.5. 
Was soll ich so einem Fall angezeigt werden?

**Comment by WernerBruckmueller** [comment]
@Ruhsi 
Zwischen den Reisen (hin und rück) muss der Ort zusammenpassen.
Meine Idee: Rückreise rückwirkend betrachtend, sofern der Ort noch zusammenstimmt (wenn man nach Wien gereist ist, ist der Arbeitsort "A (Inland außer Haus)" und darf nicht "erste Tätigkeitsstätte" sein).

Sprich: Zwischen Hinreise und Rückreise muss der Arbeitsort gleich sein. Und dieser Zeitraum soll betrachtet werden.


Testfälle:
Arbeitsort ändert sich, ohne Reise --> Fehler
Start Reise: bei nächster Buchung darf der Arbeitsort nicht "aktuelle Tätigkeitsstätte sein"
Rückreise: vorhergehende Buchung (tagesunabhängig) darf nicht "aktuelle Tätigkeitsstätte" sein

Ich glaube mit diesen 3 Testfällen sollte alles abgedeckt sein? oder @Ruhsi @ArminGepardec ?

Ich glaube, dass diese Überprüfung dann nicht relevant ist:
Start Reise: es darf keine Reise noch offen sein

**Comment by ArminGepardec** [comment]
@Ruhsi @WernerBruckmueller Wenn ihr euch einig seid ist das für mich ok, da du Werner in der Thematik mehr Tiefenverständnis hast würde ich die Bugfixes eher bei dir belassen. 
Passt das für euch?

**Comment by WernerBruckmueller** [comment]
@Ruhsi reicht dir meine Antwort?

**Comment by Ruhsi** [comment]
@WernerBruckmueller bin mir noch nicht sicher. Wir sind gerade dabei die Projektleitererweiterung zu implementieren und haben uns diese Bugfixes noch nicht genauer angesehen. Ich komme zu diesen Tickets noch auf dich zu.

**Comment by LeitnerMi** [comment]
Noch offen! Es wurde lediglich von einem täglichem Check zu einem monatlichen Check gewechselt (Fehleranfälliger?).

Offene Probleme: 

- Reisen über Monatsgrenzen hinweg.
- Falls eine Reise falsch gebucht wird , gibt es eine hohe Wahrscheinlichkeit, dass alle folgenden Reisen im Monat auch zu Fehlern werden!

Das Reisen über Monatsgrenzen hinweg ist schwierig zu realisieren, man könnte lediglich eine Warnung anlegen:
> [Sie haben eine Reise über Monatsgrenzen gebucht, sind Sie sicher?]
Für die Folgefehler kann man 'sicherlich' eine Logik implementieren, welche das Ganze umgeht und auch eine Warnung angeben:
> Es können durch Falschbuchungen Folgefehler auftreten, bitte kontrollieren. 

Nur Ideen und Anregungen.

**Comment by WernerBruckmueller** [comment]
@LeitnerMi Ad "Falls eine Reise falsch gebucht wird , gibt es eine hohe Wahrscheinlichkeit, dass alle folgenden Reisen im Monat auch zu Fehlern werden!": Wichtig ist, dass ein Fehler kommt und man Schrittweise dann die Fehler abarbeiten kann. Es ist mir nicht wichtig, ob sofort alle Fehler aufgezeigt werden.


Ad Folgefehler: Wichtig ist, dass ein Fehler auftaucht, dieser in ZEP behoben wird und man wieder in MEGA kontrolliert (solange es dann vom User Schrittweise korrigiert wird)

**Comment by WernerBruckmueller** [comment]
Test grundsätzlich erfolgreich.

Wie wird damit umgegangen, wenn die Reise bei einem Monatswechsel ist? --> Neues Ticket erstellen?

Gibt es Tests für diese Szenarien?
https://github.com/Gepardec/mega/issues/274#issuecomment-838131971
