### ISSUE TITLE
Failed to set project to "fertig"

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#289]
![image](https://user-images.githubusercontent.com/16414159/106420089-31c8a780-645a-11eb-8ce2-d3fa4e4e0a5d.png)

**Comment by WernerBruckmueller** [comment]
{stepId: 4,…}
currentMonthYear: "2021-1-01"
employee: {language: "de", active: true, email: "werner.bruckmueller@gepardec.com", firstname: "Werner",…}
projectName: "ITSV-RZ.OM"
stepId: 4

**Comment by cchet** [comment]
@Ruhsi 
@gattma 
@rainer-gepardec 

The logs say a date cannot be parsed.

> 2021-02-01 07:33:38,425 ERROR [com.gep.meg.app.exc.map.ApplicationExceptionMapper] (executor-thread-36) An unhandled exception occurred: java.time.format.DateTimeParseException: Text '2021-1-01' could not be parsed at index 5
--
  | at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
  | at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
  | at java.base/java.time.LocalDate.parse(LocalDate.java:428)
  | at com.gepardec.mega.domain.utils.DateUtils.parseDate(DateUtils.java:22)
  | at com.gepardec.mega.domain.utils.DateUtils.getFirstDayOfCurrentMonth(DateUtils.java:53)
  | at com.gepardec.mega.service.impl.stepentry.StepEntryServiceImpl.closeStepEntryForEmployeeInProject(StepEntryServiceImpl.java:86)
  | at com.gepardec.mega.service.impl.stepentry.StepEntryServiceImpl_ClientProxy.closeStepEntryForEmployeeInProject(StepEntryServiceImpl_ClientProxy.zig:308)
  | at com.gepardec.mega.rest.StepEntryResource.close(StepEntryResource.java:58)
