### ISSUE TITLE
Ruhezeiten überprüfen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#294]
![image](https://user-images.githubusercontent.com/16414159/107505059-752ebe80-6b9c-11eb-9d95-a208ebbb98ec.png)

**Comment by WernerBruckmueller** [comment]
@WernerBruckmueller genau definieren --> Testfälle definieren
@ArminGepardec

**Comment by phiwu-gpdec** [comment]
@WernerBruckmueller bitte Problem genauer beschreiben.

**Comment by WernerBruckmueller** [comment]
Info von Alex:
- Ruhezeit zwischen einzelnen Arbeitstagen: 11 Std (es sind Ausnahmen möglich --> Hinweis bei Unterschreitung; aber da meldet ZEP schon vorher)
- bei Reisezeiten kann die Ruhezeit zum nächsten Tag auf 8 Std verkürzt werden
- toll wäre ein Warnhinweis, wenn Stunden außerhalb des Gleitzeitrahmen gebucht wurden (also zwischen 22 und 6 Uhr und an Sa, So und Feiertag)

Weitere Pausenregelungen sind in ZEP erfasst: https://www.zep-online.de/zepgepardecservices/view/index.php?menu=StammdatenContentMenuMgr&mgr=PausenregelungMgr

Diese sind nur als Admin erreichbar. Sobald das Issue angefangen wird, werden diese als Screenshot bereitgestellt

**Comment by WernerBruckmueller** [comment]
Es ist dann auch zu dokumentieren, was funktioniert und was nicht (evtl im Wiki?)

**Comment by WernerBruckmueller** [comment]
Vorab ist zu analysieren, was bereits umgesetzt wurde.

**Comment by andreas-repo** [comment]
@WernerBruckmueller 
Schickst du mir bitte den Screenshot, ich habe die Issue angefangen. Danke

**Comment by WernerBruckmueller** [comment]
![image](https://user-images.githubusercontent.com/16414159/140033546-d0962b34-f9ac-4201-9970-dbc1e0c779eb.png)


Das ist für Standard-MA
Es wird dann noch zwischen "Erw. Arbeitszeit 12/60" und "Leitende" unterschieden - mehr dazu beim Statustermin

**Comment by andreas-repo** [comment]
https://github.com/Gepardec/mega/wiki/%C3%9Cbersicht-Pausen-Tests <== Übersicht der Tests im Wiki angelegt
https://github.com/Gepardec/mega/wiki/%C3%9Cbersicht-Ruhezeit-Test <== Übersicht der Tests im Wiki angelegt
https://github.com/Gepardec/mega/wiki/%C3%9Cbersicht-Arbeitszeiten-Tests <== Übersicht der Tests im Wiki angelegt

Mindestruhezeit 11,0 Stunden ist implementiert und getestet
Maximale Arbeitszeit 10,0 Stunden ist implementiert und getestet
Warnung bei Überschreiten der Pausenregeln ist implementiert und getestet
Warnung beim Nichteinhalten der Pausenregeln (bei der Eingabe) ist implementiert und getestet
Mindestlänge einer Pause (15 min) ist implementiert
