### ISSUE TITLE
Sort OM view

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#299]
Es soll bei der Sortierung OM1 und OM2 berücksichtigt sein

**Comment by WernerBruckmueller** [comment]
siehe auch #466

**Comment by Ruhsi** [comment]
@WernerBruckmueller was ist mit OM1 und OM2 gemeint?
Derzeitige Sortierung:

1. Kundenzeiten offen und interne Zeiten offen
2. Projektzeiten erledigt und interne Zeiten offen
3. Interne Zeiten erledigt und Projektzeiten offen
4. Kundenzeiten erledigt und interne Zeiten erledigt

**Comment by WernerBruckmueller** [comment]
Mitarbeitern sollen alphabetisch angezeigt werden.
Wenn Kundenzeiten ODER Interne Zeiten offen sind, sollen diese Mitarbeiter oben angezeigt werden.

Soweit ich weiß, wird in der aktuellen Version nur die Kundenzeit berücksichtigt.

**Comment by WernerBruckmueller** [comment]
Nicht mehr relevant
