### ISSUE TITLE
Falsche (?) Warnung bezüglich Reisen

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/mega#309]
**Describe the bug**
MEGA zeigt eine Warnung bezüglich einer Reise:
![image](https://user-images.githubusercontent.com/20546046/113664372-ecb83000-96ab-11eb-89ac-8a3a7378f682.png)

ZEP meint alles ist OK:
![image](https://user-images.githubusercontent.com/20546046/113664435-06597780-96ac-11eb-817a-10610be99c0e.png)

Ein Reload von MEGA hat nix geholfen.

Hinweis: ich habe gerade davor die Anmerkung von Evelyn erledigt.

**Expected behavior**
ZEP und MEGA melden dasselbe

**Screenshots**

**Comment by WernerBruckmueller** [comment]
duplicate #274 
thx chris fürs einmelden!
