### ISSUE TITLE
PL Mail erweitern

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#310]
"Reminder: Projekte kontrollieren und abrechnen"
Soll um den Link erweitert werden: https://docs.google.com/spreadsheets/d/1Da3XrY9WuBrftJc0oBVySx58Ms1LWWhNkb3gfpZ4anA/edit#gid=0

- Planrechnung ist zu aktualisieren

**Comment by patholzer** [comment]
@WernerBruckmueller Die derzeitige E-Mail beinhaltet eine Liste an Bullet-Points. An welcher Stelle macht der neue Listen-Eintrag Sinn? die aktuellen Einträge sind folgende: 

- Inhaltliche Kontrolle der Arbeitszeiten und Belege der Projektmitarbeiter
- ggf. Zeitnachweise übermitteln
- Controlling durchführen
- Rechnung(en) erstellen
- Checkliste laut Wiki
- Status im Monatsende-Dashboard aktualisieren
- Status in MEGA aktualisieren

**Comment by WernerBruckmueller** [comment]
Rechnung(en) erstellen
--> hier <--
Checkliste laut Wiki

**Comment by WernerBruckmueller** [comment]
Kann auf der Dev-Stage nicht überprüft werden
