### ISSUE TITLE
PL-Ansicht um Projektzeiten erweitern  (optional)

### ISSUE THREAD

**Issue by ArminGepardec** [Gepardec/mega#319]
MA-Zeiten (Fakturierbar und n. Fakturierbar) anzeigen --> Hilfestellung für Rechnungskontrolle

**Comment by WernerBruckmueller** [comment]
Ideal wäre es, wenn die n. fakt. Zeiten nur angezeigt werden, wenn welche angefallen sind.

**Comment by WernerBruckmueller** [comment]
Statt dem Freigabedatum sollen die fakturierbare und nicht fakturierbare zeiten angezeigt werden:
![image](https://user-images.githubusercontent.com/16414159/125739943-d501e5bc-faae-43fb-8803-71a326662570.png)

**Comment by phiwu-gpdec** [comment]
@Ollitod @patholzer Würdet ihr euch das mit den Praktikanten gemeinsam ansehen?

**Comment by patholzer** [comment]
> @Ollitod @patholzer Würdet ihr euch das mit den Praktikanten gemeinsam ansehen?

![ready](https://user-images.githubusercontent.com/47662203/125923320-7be0ab1a-79f1-421f-861c-92958aa349a2.gif)

**Comment by WernerBruckmueller** [comment]
Bitte um Rücksprache mit mir bzgl grafischer Darstellung.

**Comment by LeitnerMi** [comment]
@Ollitod @patholzer Wie läuft das dann so ca. ab? Werden wir irgendwie fixe Meetings haben, bzw wie läuft die gemeinsame Arbeit dann ab? LG

**Comment by LeitnerMi** [comment]
In der Projekt-Management Ansicht wurde bei uns lokal, als Startmonat immer der Mai ausgewählt und auch die Abfrage wurde auf den Monat 5 erstellt. Nach Auswählen mit DatePicker hat alles gestimmt. @Ollitod @patholzer

**Comment by patholzer** [comment]
Hi @LeitnerMi, ist Freitag früher Vormittag bei euch in Ordnung? Im Idealfall vor oder nach dem Frühstück

**Comment by LeitnerMi** [comment]
@patholzer Jap, glaube vor dem Frühstück würde passen.

**Comment by phiwu-gpdec** [comment]
@Ollitod @patholzer Die Funktion wurde heute von @LeitnerMi  und @insinnox eingebaut. Bitte bei Gelegenheit noch Styling verbessern bzw. das in eine eigene Component verpacken.

**Comment by phiwu-gpdec** [comment]
![billable_project_hours_v](https://user-images.githubusercontent.com/46929039/126657082-992cf007-b63a-460d-ab47-7a29320a27fa.png)

**Comment by WernerBruckmueller** [comment]
@insinnox @LeitnerMi
Bitte auch Dezimalzahlen für die Stunden verwenden, so wie in #400
