### ISSUE TITLE
Monatsende-dashboard ablösen (Projektleiter)

### ISSUE THREAD

**Issue by ArminGepardec** [Gepardec/mega#320]
Ablöse des Projektleiter Teils des Monatsende Dashboards
- Status setzen für Projektzeitenkontrolle (je Projekt)
- Status setzen für Rechnungskontrolle (je Projekt)

TODO:
Prozess analysieren und zeichnen und User Stories aus dem Prozess ableiten
- Projektzeitenkontrolle -> Erledigt (7.5.2021)
- Rechungskontrolle -> Offen

**Comment by WernerBruckmueller** [comment]
Siehe PL Abschluss SOLL
https://app.diagrams.net/#G1EJV0-lOmLJvu7Ka7iUZEko0bEpCNNK5s

**Comment by ArminGepardec** [comment]
Epic Produktseitig vollständig. Kann in Produktion übernommen werden
