### ISSUE TITLE
Bug new employee: Internal Error

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#331]
Oliver:
Ich bekomme einen 500 Internal Server Error. Freigabedatum ist bei mir in ZEP auf den 31.03.2021 gesetzt.
Eintrittsdatum ist der 19.04.2021
Fehler liegt bei doppeltem User

**Comment by Ruhsi** [comment]
In der prod-db stand bei Olivers Zepid 61-otod anstatt 061-otod. Laut Oliver hat sich da in ZEP was geändert. Ist jetzt behoben und Oliver kann sich einloggen.
