### ISSUE TITLE
Frage an Werner Folgemonat Verhalten bei Monatsauswahl

### ISSUE THREAD

**Issue by ArminGepardec** [Gepardec/mega#336]
Wenn das Flag "Im Folgemonat übernehmen" gesetzt ist und man nachträglich das Monat wechselt und dort das Flag ändert. Soll sich dann das Flag für das aktuelle Monat auch ändern?

**Comment by WernerBruckmueller** [comment]
Wenn die StepEntries von Monat x generiert wird, dann soll Monat x-1 überprüft werden, ob dort das Flag gesetzt ist.
