### ISSUE TITLE
Frage: Soll die Projektzeitenkontrolle und die Rechnungskontrolle auch in der collapsed View ersichtlich sein?

### ISSUE THREAD

**Issue by ArminGepardec** [Gepardec/mega#337]
Vorschlag (für 1-Zeiliges Layout)
![image](https://user-images.githubusercontent.com/24893387/117454432-6b6fe980-af46-11eb-889d-21cec675149e.png)

**Comment by WernerBruckmueller** [comment]
Ja, so wie im screenshot
