### ISSUE TITLE
Datum für Step Entry Generierung anpassen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#344]
Die Step Generierung soll vor dem erstem im Monat stattfinden.

Soll: -2 Arbeitstage vom Monatsletzten sollen die StepEntries erstellt sein (zB am 30. Jänner ist der Jänner angelegt und verfügbar)

**Comment by WernerBruckmueller** [comment]
Achtung, falls das umgesetzt wird, ist auf das Releasedatum aufzupassen, dass sichergestellt ist, dass die Steps auch generiert werden.
Problem wäre, wenn das Releasedatum zwischen dem neuen Soll-Generierungsdatum und dem 1. liegt.

**Comment by LeitnerMi** [comment]
@WernerBruckmueller Reichen 2 Tage vor Monatsende oder soll ein größerer Abstand gewählt werden?

**Comment by WernerBruckmueller** [comment]
2 Tage sind genug
