### ISSUE TITLE
Homeoffice kontrollieren

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#360]
MAs im Mail darauf hinweisen (Mail), dass HO-Tage einzutragen sind.
Inkl Link zu Personio.

**Comment by WernerBruckmueller** [comment]
Alternative Idee
"Mein Mega" um Infobereich erweitern:

- xxx Stunden im Monat
- xxx fakturierbare Stunden (x%)
- 3 Urlaubstage
- 2 ZA-Tage
- 5 Homeofficetage

**Comment by WernerBruckmueller** [comment]
Alternative:
In mein MEGA ein Check über Homeoffice-Tage

**Comment by phiwu-gpdec** [comment]
@WernerBruckmueller Wir nehmen vorschlag 1. :-)

**Comment by phiwu-gpdec** [comment]
@LeitnerMi @insinnox Der Link zu Personio: https://gepardec.personio.de/login/index
