### ISSUE TITLE
"Die Kontrolle deiner Zeiten ist in Gange" obwohl alle PLs auf grün sind?

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/mega#361]
![image](https://user-images.githubusercontent.com/20546046/121131662-65647580-c830-11eb-9652-4b3533313a05.png)

**Comment by WernerBruckmueller** [comment]
Status ok, da die internen und PL Zeiten vom OM noch nicht überprüft sind:
![image](https://user-images.githubusercontent.com/16414159/121132955-10296380-c832-11eb-9a0b-d9e8d5aba45b.png)

**Comment by ChrisKofler** [comment]
aha. Ist für den MA nicht klar.

**Comment by WernerBruckmueller** [comment]
Was wäre für dich klarer? Kann gerne deinen Vorschlag als Enhancement für
MEGA x mitnehmen.

Vorschlag Text:
Die Kontrolle deiner Zeiten ist in Gange (OM/PL)

Statt: Die Kontrolle deiner Zeiten ist in Gange

WERNER BRUCKMÜLLER, MSc

Projektmanager


Gepardec IT Services GmbH

*Wien:* Donau-City-Straße 1
***@***.***,16.4116248,17z/data=!3m1!4b1!4m5!3m4!1s0x476d06e5d18b3345:0xa410ca8bf38f4af1!8m2!3d48.2325035!4d16.4138135>,
1220 Wien

*Linz:* Europaplatz 4
***@***.***,14.3015801,17z/data=!3m1!4b1!4m5!3m4!1s0x477397ed4d366f6d:0xc23903160e89657a!8m2!3d48.2977882!4d14.3037688>
(Eingang C), 4020 Linz

MOBILE   +43 664 1630194

MAIL        ***@***.***
WEB        www.gepardec.com

**Comment by ChrisKofler** [comment]
Ja - wenn man mit der Maus drüber fährt, der Status der PLs auf grün ist
und hier noch ein roter Status steht "Office Management: in Arbeit" (oder
so ähnlich).

Lg, Chris

__

Christoph Kofler, DI

Flow Master / LEGO® SERIOUS PLAY® Facilitator


Gepardec IT Services GmbH

Wien: Donau-City-Straße 1
***@***.***,16.4116248,17z/data=!3m1!4b1!4m5!3m4!1s0x476d06e5d18b3345:0xa410ca8bf38f4af1!8m2!3d48.2325035!4d16.4138135>,
1220 Wien

Linz: Europaplatz 4
***@***.***,14.3015801,17z/data=!3m1!4b1!4m5!3m4!1s0x477397ed4d366f6d:0xc23903160e89657a!8m2!3d48.2977882!4d14.3037688>
(Eingang C), 4020 Linz


MOBILE    +43 664 88 23 15 21

MAIL ***@***.*** WEB www.gepardec.com
