### ISSUE TITLE
Google AutoValue entfernen und durch Lombok oder Plain-Java ersetzen.

### ISSUE THREAD

**Issue by phiwu-gpdec** [Gepardec/mega#370]
Google AutoValue produziert in Kombination mit Quarkus >= 1.11.7.Final bei den Mockito-Tests Null-Pointer-Exceptions. 

Eine Möglichkeit wäre, Lombok statt AutoValue zu verwenden, oder die Getter und Setter von IntelliJ erstellen zu lassen.

**Comment by phiwu-gpdec** [comment]
Lombok +1

**Comment by Ruhsi** [comment]
Lombok +1 --> AutoValue verwendet das Builder-Pattern, wir haben da sehr viele Stellen im Code. Zum Generieren für den Builder wird soweit ich weiß ein Plugin in Java benötigt. Lombok bietet dafür die Annotation @Builder.

**Comment by Ollitod** [comment]
Lombok +1

Ich hab keine konkreten Einwände gegen einen Wechsel. Die Entscheidung für die Umsetzung mit AutoValue wurde voriges Jahr aus folgenden Gründen getroffen (sofern ich mich erinnere):

- AutoValue Klassen (und Instanzen) sind immutable, sodass nach der Erzeugung die Properties nicht mehr verändert werden können.
- Bei AutoValue dürfen nur Instanzen erzeugt werden, wenn alle Properties für die Klasse gesetzt sind (sofern nicht nullable).

Wenn Lombok dies auch unterstützt oder wir diese Kriterien nicht erfüllen müssen, bin ich auf alle Fälle für einen Umstieg.

**Comment by patholzer** [comment]
Da wir hier ein Spielwiesen-Projekt haben und Erfahrungen sammeln wollen -> Lombok +1

**Comment by rfischerGep** [comment]
Von Lombok hab ich keine Ahnung, würd das gern in Pair Programming anschauen
