### ISSUE TITLE
Design first page

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#38]
TBD

check ZEP JSON

**Comment by WernerGepardec** [comment]
JSON Response

{
   "anrede":"Herr",
   "bemerkung":"VSNR.: 4650 261294",
   "beschaeftigungszeitListe":{
      "beschaeftigungszeit":[
         {
            "enddatum":"2017-09-29",
            "id":22,
            "startdatum":"2017-07-25",
            "userId":"026-cruhsam"
         },
         {
            "enddatum":"2018-06-29",
            "id":30,
            "startdatum":"2018-04-09",
            "userId":"026-cruhsam"
         },
         {
            "enddatum":"2018-09-30",
            "id":35,
            "startdatum":"2018-08-06",
            "userId":"026-cruhsam"
         },
         {
            "id":40,
            "startdatum":"2018-10-29",
            "userId":"026-cruhsam"
         }
      ]
   },
   "bic":"RZOOAT2L277",
   "email":"christoph.ruhsam@gepardec.com",
   "freelancer":0,
   "freigabedatum":"2019-07-31",
   "geburtsdatum":"1994-12-26",
   "iban":"AT653427700002221729",
   "internersatzListe":{
      "internersatz":[
         {
            "bemerkung":"Initialer interner Stundensatz",
            "id":21,
            "satz":33.0,
            "satztype":1,
            "userId":"026-cruhsam"
         }
      ]
   },
   "kurzzeichen":"CRH",
   "nachname":"Ruhsam",
   "ort":"Schenkenfelden",
   "personalNr":"026",
   "plz":"4192",
   "preisgruppe":"07",
   "rechte":1,
   "regelarbeitszeitListe":{
      "regelarbeitszeit":[
         {
            "dienstag":8.0,
            "donnerstag":8.0,
            "freitag":6.5,
            "id":24,
            "mittwoch":8.0,
            "montag":8.0,
            "userId":"026-cruhsam"
         },
         {
            "dienstag":1.5,
            "donnerstag":1.0,
            "freitag":1.0,
            "id":66,
            "mittwoch":1.0,
            "montag":1.5,
            "startdatum":"2018-10-29",
            "userId":"026-cruhsam"
         },
         {
            "dienstag":6.0,
            "donnerstag":6.0,
            "freitag":6.0,
            "id":93,
            "mittwoch":6.0,
            "montag":6.0,
            "startdatum":"2019-08-01",
            "userId":"026-cruhsam"
         }
      ]
   },
   "sprache":"de",
   "strasse":"Hinterkönigschlag 14",
   "titel":"BSc",
   "urlaubsanspruchJahresanfang":-10.0,
   "urlaubsanspruchProJahr":0.0,
   "userId":"026-cruhsam",
   "vorjahresueberstunden":53.25,
   "vorname":"Christoph"
}

**Comment by sthausmann** [comment]
closed, because not important right now - will pop up again, if it really is relevant
