### ISSUE TITLE
Bug: Kommentieren funktioniert nicht (prod)

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#381]
Wenn man auf das Symbol für ein Kommentar klickt (Egal ob PM-View oder OM-View) kommt ein Fehler.

**Comment by WernerBruckmueller** [comment]
Release 2.0.5

**Comment by WernerBruckmueller** [comment]
![image](https://user-images.githubusercontent.com/16414159/123923779-9a746b80-d989-11eb-81b2-bc9e5c05d245.png)

![image](https://user-images.githubusercontent.com/16414159/123923848-aa8c4b00-d989-11eb-9371-0569ff19f440.png)

**Comment by phiwu-gpdec** [comment]
Fehlerbeschreibung:

Office Management -> in der Liste auf "Kommentar klicken". Das Fenster, das sich öffnet, lädt versucht Daten zu laden aber irgend etwas geht schief und man wird auf die Fehlerseite umgeleitet. Der Dialog lässt sich auch nicht mehr schließen.

**Comment by WernerBruckmueller** [comment]
Fehler lt Console:

main-es2015.ee11359a4640d3119f5b.js:1 test
main-es2015.ee11359a4640d3119f5b.js:1 Wed Jun 30 2021 11:47:43 GMT+0200 (Mitteleuropäische Sommerzeit) - Type: 1 - Message: Cannot read property 'nativeElement' of undefined
main-es2015.ee11359a4640d3119f5b.js:1 Wed Jun 30 2021 11:47:43 GMT+0200 (Mitteleuropäische Sommerzeit) - Type: 1 - Message: Cannot read property 'nativeElement' of undefined
main-es2015.ee11359a4640d3119f5b.js:1 true

**Comment by WernerBruckmueller** [comment]
https://mega-zep-backend-57-mega-prod.cloud.itandtel.at/comments/getallcommentsforemployee?email=...@....com&date=2021-05-01

**Comment by phiwu-gpdec** [comment]
@Ruhsi kannst du bitte in der Datenbank checken, ob bei Werners User noch alles passt? (DB Restore).

@Ollitod Ich habe versucht, das bei mir lokal nachzustellen, aber ich bekomme diese(n) Fehler nicht. Kann das mit der Änderung zusammenhängen, die ihr eingebaut habt, das die Seite nicht mehr neu geladen wird, wenn keine Daten verändert wurden?

**Comment by phiwu-gpdec** [comment]
@ArminGepardec kannst du bitte versuchen, ob du den Fehler von Werner auch bekommst?

**Comment by WernerBruckmueller** [comment]
@ArminGepardec Armin hat keine OM-Rolle auf der Prod

**Comment by WernerBruckmueller** [comment]
Armin hat keine OM Rolle

WERNER BRUCKMÜLLER, MSc

Senior Projektmanager


Gepardec IT Services GmbH

*Wien:* Donau-City-Straße 1
***@***.***,16.4116248,17z/data=!3m1!4b1!4m5!3m4!1s0x476d06e5d18b3345:0xa410ca8bf38f4af1!8m2!3d48.2325035!4d16.4138135>,
1220 Wien

*Linz:* Europaplatz 4
***@***.***,14.3015801,17z/data=!3m1!4b1!4m5!3m4!1s0x477397ed4d366f6d:0xc23903160e89657a!8m2!3d48.2977882!4d14.3037688>
(Eingang C), 4020 Linz

MOBILE   +43 664 1630194

MAIL        ***@***.***
WEB        www.gepardec.com

**Comment by phiwu-gpdec** [comment]
@ArminGepardec  jetzt schon.

@AlexandraGepardec du wurdest auch hinzugefügt.

**Comment by ArminGepardec** [comment]
Bekomm den Fehler auch :(

**Comment by ArminGepardec** [comment]
Update Fehlerbeschreibung: 
Der Fehler kommt auch auf der Test. Allerdings NUR wenn der Eintrag bereits freigegeben wurde. Dann tritt er Fehler auf sobald man den Dialog schließt.

**Comment by WernerBruckmueller** [comment]
Update:
Fehler ist aktuell nicht reproduzierbar im neuen Monat.

**Comment by Ollitod** [comment]
Update:
Bug wurde entdeckt. Ursache: Das Textfeld im Dialog wird nur gerendert, wenn der Employee für das aktuelle Abrechnungsmonat noch nicht freigegeben wurde. Im Typescript wird eine Referenz auf das Textfeld gehalten. Ist der Mitarbeiter also freigegeben, kann die Referenz nicht gesetzt werden, weil das Textfeld im DOM nicht vorhanden ist.
Der Bug besteht also schon seit geraumer Zeit (27.11.2020 letzte Änderung)

**Comment by WernerBruckmueller** [comment]
Test auf Test-Umgebung erfolgreich
