### ISSUE TITLE
Anpassungen an der Datenbank

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#382]
Um die für die Tickets #375 und #380 notwendigen Daten speichern zu können, bedarf es Anpassungen an der Datenbank.
Für Ticket #380:

- Projekttabelle könnte um eine Spalte erweitert werden, da es nur eine globale Anmerkung pro Projekt gibt, die sowohl aus OM-Sicht und PM-Sicht eingesehen/bearbeitet werden kann und nicht historisiert werden muss. Detaillierte Beschreibung siehe Ticket.

Für Ticket #375 

- Hier gibt es auf alle Fälle einiges zu klären. Können wir eventuell die Unternehmensweiten "Flags" über die Projektentires abbilden?

Des weiteren gibt es den Schritt "Unternehmens-Controlling erstellt", welchen wir bereits abgebildet haben, nicht mehr.

**Comment by WernerBruckmueller** [comment]
Ich sehe keine fachliche Frage, mehr Richtung DB. Gerne kannst du mich oder Armin anrufen, sollten wir hier helfen können.
@phiwu-gpdec denke, dass es eher technisch im Team zu beantworten ist. Oder @Ollitod ?

**Comment by ArminGepardec** [comment]
Aus fachlicher Sicht ist nichts mehr offen. Ich nehme das needs Clarification wieder raus.
