### ISSUE TITLE
Aufgaben beim Produktivgang für PM

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#383]
- [ ] Dev Doku wie man jemanden einen Rolle vergibt für Prod zB
- [x] Excel deprecated setzen
- [x] Wiki updaten
- [x] Gepardec Präsentation abhalten (an wen?) --> zumindest OM + PL + GF informieren
- [ ] Abschlusspräsentation für Breakout planen
- [ ] Board schließen / Aufgaben auf das Default-MEGA Board verschieben
- [x] Releasefeier planen (MEGA 123)

**Comment by WernerBruckmueller** [comment]
@Manuel-Vilim @ArminGepardec nicht vergessen

Habe einige Issues Richtung MEGA (https://github.com/Gepardec/mega/projects/6) verschoben.

**Comment by Ruhsi** [comment]
@WernerBruckmueller ist das noch relevant? Sonst bitte auf DONE stellen.
