### ISSUE TITLE
Doku: Wie erstelle ich ein Release, DB, ... 

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#389]
Wie erstelle ich ein Release, DB, ... wie wohin deployen <-- Leitfaden
Leitfaden wie man jemanden OM Rolle vergibt

**Comment by Ruhsi** [comment]
@WernerBruckmueller @Gepardec/mega-dev-team Release-Workflow, Testdatengenerierung und OM-Rolle hinzufügen sind im Wiki dokumentiert
