### ISSUE TITLE
Info-Bereich in Mein MEGA

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#400]
*     Anzeigemöglichkeit = AM

**Allgemein:**
“Mein Mega” - Bereich um AM* erweitern um Informationen (pro Monat!) übersichtlich darzustellen:

- Wv. Stunden gearbeitet wurden
- Prozentsatz & Anzahl der fakturierbaren Stunden 
- Anzahl Urlaubstage
- Anzahl Zeitausgleichtage
- Anzahl Homeofficetage

**Abnahmekriterien:**

- Unter “Mein Mega” ein AM* einfügen, sodass der Inhalt ohne Zwischenschritt einsehbar ist
- Die Ansicht ist nur für das derzeitige Monat.
 - Nächsten Monat starten die Informationen wieder bei 0
 - Nach der Aktualisierung der Seite werden die aktuellen Daten aus ZEP herausgelesen.

**Bereits realisierte, (technische,) mögliche Schwierigkeiten:**
Homeofficetage? API Personio? Zep speichert keine HO

![image](https://user-images.githubusercontent.com/87299303/126481953-5ea03cf2-6db7-4119-bad2-fb93cf31e512.png)

**Comment by WernerBruckmueller** [comment]
Anmerkung zum Screenshot:
Im linken Bereich würde ich beide Checks vorsehen.
Im rechten Bereich die Infos.

**Comment by WernerBruckmueller** [comment]
Keine Priorität für MEGA 3 (Release Ende Juli)

**Comment by insinnox** [comment]
@Ollitod @patholzer Bitte Frontend morgen überprüfen

**Comment by insinnox** [comment]
![image](https://user-images.githubusercontent.com/68692708/126656285-e19961e0-0c04-4af3-982b-16ed02d23fb2.png)

**Comment by WernerBruckmueller** [comment]
@insinnox @LeitnerMi 
Umbenennung von "Verrechenbar" auf "Chargeability", da es firmenintern so verwendet wird.

Kann man die Stunden von "08.50" in "8,50" ändern?

**Comment by WernerBruckmueller** [comment]
Test:
Umbenennung von "Verrechenbar" auf "Chargeability", da es firmenintern so verwendet wird.

**Comment by WernerBruckmueller** [comment]
Test ok. Werden ein Folgeticket mit Urlaub, HO, ZA erstellen
