### ISSUE TITLE
ZEP Zugriffe verlangsamen MEGA (asynchron laden?)

### ISSUE THREAD

**Issue by ArminGepardec** [Gepardec/mega#410]
Beim laden der Projektleiteransicht werden aktuell die Verrechenbaren und nicht verrechenbaren Stunden je Projektmitarbeiter angezeigt. Der Ladevorgang erfolgt snychron, daher müssen alle Daten geladen sein, bevor die Seite angezeigt werden kann. 

Problem:
Die Wartezeit für diese Ansicht wird unangenehm lange (5sek+)

**Comment by WernerBruckmueller** [comment]
Es wurde ein Caching-Mechanismus eingebaut, was einen gewissen Nachteil bringt (Daten sind nicht aktuell).

Eine asynchrone Lösung ohne Caching ist zu bauen (nach MEGA 3).

**Comment by WernerBruckmueller** [comment]
Wunsch: Caching ausbauen und für ALLE MEga-Bereiche, welche ZEP-Aufrufe haben, eine Lösung zu finden (zB asynchrone Aufrufe)
