### ISSUE TITLE
Kommentar in PM

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#417]
Wenn man ein Kommentar verfasst, soll ein Hinweis kommen wenn man herausklickt, dass nicht gespeichert wurde, sofern keine Aktion (Speichern, Verwerfen) gemacht wurde.

**Comment by insinnox** [comment]
@Ollitod dieses Ticket überschneidet sich mit dem Ticket 430. Wenn man aus dem Feld herausklickt dann soll ein Hinweis erscheinen. Jedoch erscheint der Hinweis auch wenn ich versuche auf Speichern zu klicken und wird somit auch nicht gespeichert.
Kannst du dir das bitte anschauen.

**Comment by phiwu-gpdec** [comment]
Anforderung muss noch einmal evaluiert werden.
