### ISSUE TITLE
Internal 500 Error wenn Aktion ausgelöst wird

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#421]
<img width="1792" alt="Bildschirmfoto 2021-07-23 um 13 20 27" src="https://user-images.githubusercontent.com/24893387/126775018-68bd67c3-a7c5-4d0f-9784-68c981b008c1.png">

**Comment by phiwu-gpdec** [comment]
Unit-Tests für StepEntryRepository.closeAssigned fehlt.
