### ISSUE TITLE
PL/OM-Kommentare: Umbruch wird nur im Edit-Modus dargestellt

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#430]
![image](https://user-images.githubusercontent.com/16414159/126779944-34436d76-ecb7-4280-be2a-1c0b50d303db.png)
![image](https://user-images.githubusercontent.com/16414159/126779966-56dc1461-1807-4e3f-8a69-98ebb8737914.png)

Soll: Umbrüche sollen dargestellt werden

**Comment by insinnox** [comment]
![image](https://user-images.githubusercontent.com/68692708/127118902-1245e816-f2f7-4e28-b52c-8c0647a0703d.png)
![image](https://user-images.githubusercontent.com/68692708/127132139-8d49e0bd-c5b7-4a3f-a362-8a5ddc2cca85.png)

Problem wurde behoben.

**Comment by WernerBruckmueller** [comment]
OM-View ok

PL-View nicht ok

**Comment by WernerBruckmueller** [comment]
Test erfolgreich
