### ISSUE TITLE
Info-Bereich um HO, Urlaub und ZA erweitern

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#446]
Siehe #400

**Comment by LeitnerMi** [comment]
siehe #416

**Comment by WernerBruckmueller** [comment]
Homeoffice wird falsch berechnet, wenn der Zeitraum über Monatsgrenzen geht:
![image](https://user-images.githubusercontent.com/16414159/128398734-85c2253b-af2d-469e-9513-5666e71a57e0.png)
Soll: 3 Tage Homeoffice
Ist: 
![image](https://user-images.githubusercontent.com/16414159/128398815-40ee5521-a643-404c-95d9-60b99e1e2cb4.png)

**Comment by WernerBruckmueller** [comment]
Selbes Verhalten bei Urlaub. ZA wurde nicht getestet.

**Comment by WernerBruckmueller** [comment]
@phiwu-gpdec bitte um aktuellen Status

**Comment by Ruhsi** [comment]
@WernerBruckmueller Berechnung für HO sollte gefixt sein. Ready for testing
