### ISSUE TITLE
Monat selbst wechseln können in Mein MEGA

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#450]
Rechts oben soll, ähnlich wie bei OM, das Monat in die Vergangenheit gewechselt werden können.

Als Vorauswahl im Monat soll das Monat wie jetzt in Abhängigkeit vom Freigabedatum verwendet werden.

**Comment by WernerBruckmueller** [comment]
@phiwu-gpdec 
wenn ich ein Monat im Jahr 2016 auswähle, bekomme ich einen 500er Fehler:
![image](https://user-images.githubusercontent.com/16414159/128398090-6f885505-2c15-4187-a049-1422ce640e56.png)

**Comment by insinnox** [comment]
Das Monat 2016/6 und alle anderen Monate funktionieren eigentlich auf dem dev- und test- System.

**Comment by WernerBruckmueller** [comment]
Es sieht aus, als ob der Bereich "Status zum Monatsabschluss" nicht mitausgewählt wird

**Comment by WernerBruckmueller** [comment]
Test: 
Tag: 29.11.
Freigabedatum: 31.10


In PM-View ein Kommentar für sich selbst erstellen (Monat Oktober ist ausgewählt).

Mein MEGA öffnen: 
- November ausgewählt (ok)
- Offenes Kommentar wird angezeigt (ok)
- Falsch: "Dieses Monat ist nicht verfügbar!" wird angezeigt
 
![image](https://user-images.githubusercontent.com/16414159/143864179-f82f5143-e536-4d68-a4cd-412e5006ccfc.png)


Soll: 
![image](https://user-images.githubusercontent.com/16414159/143864014-bb7ba9ab-7a72-4eb6-89b0-801bd730b6e7.png)



Anmerkung: Wenn es kein Kommentar gibt, so wird das Monat korrekt angezeigt:
![image](https://user-images.githubusercontent.com/16414159/143863982-bbf20ac4-308b-40b7-9f82-b54ad1bc3d58.png)

**Comment by phiwu-gpdec** [comment]
@Ollitod @patholzer @rfischerGep könnt Ihr euch das bitte bei Gelegenheit ansehen, was und ob das noch offen ist?

**Comment by WernerBruckmueller** [comment]
Bug wurde beim Testen eingemeldet. Issue war vorher in "Ready for Testing"

**Comment by Ollitod** [comment]
Ich vermute hier das Problem mit dem Datum-State im Frontend, der nicht über das Backend ermittelt wird. 
Beim Troubleshooting wurde folgendes festgestellt:
Datumsauswahl rechts oben: Dezember 2021
MEGA Zeiten Check: **November**
Info Dezember 2021
   -Inhalt **November**
Status zum Monatsabschluss: Dezember
MEGA Reisen Check: **November**

An jenen Stellen, wo November ausgewählt/angezeigt wird, wird das Datum im Frontend selbst bestimmt und nicht vom Backend abgeleitet. Dieser selbsterzeugte State im Frontend muss entfernt werden.

**Comment by WernerBruckmueller** [comment]
@Ollitod was ist hier der aktuelle stand? soll das noch offen bleiben?
