### ISSUE TITLE
Sortierung in PM-View

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#466]
Die Sortierung der PM-View soll alphabetisch sein (Projekte und Mitarbeiter). Die Mitarbeiter sollen nach Nachname sortiert werden.

Zusatz für Projekte:
Wenn Mitarbeiter überprüft, Rechnungslegung und Projektcontrolling auf Fertig/nicht relvant sind, sollen diese unten angezeigt werden (auch wieder aphabetisch)

**Comment by WernerBruckmueller** [comment]
siehe auch #299

**Comment by Ruhsi** [comment]
@WernerBruckmueller: sieht dann so aus:

![Bildschirmfoto 2021-11-19 um 10 07 42](https://user-images.githubusercontent.com/24733670/142596238-2ca74962-d828-4f29-80a3-c6c9128173ca.png)

Armin und Oliver wandern nach unten, weil alles erledigt. Ruhsi bleibt in der oberen Liste weil noch nicht alles erledigt.
Beide sortiert nach lastname und firstname

**Comment by WernerBruckmueller** [comment]
Wie ist die Sortierung der Projekte?

**Comment by WernerBruckmueller** [comment]
Projekte sind nicht alphabetisch sortiert

**Comment by Ruhsi** [comment]
@WernerBruckmueller hast du einen Screenshot von deiner Projektansicht. Bei mir sind die Projekte alphabetisch sortiert

![Bildschirmfoto 2021-11-30 um 08 10 57](https://user-images.githubusercontent.com/24733670/144002001-b3b16293-a8bf-4c4b-aab1-497042c778e9.png)

**Comment by WernerBruckmueller** [comment]
Hat sich erledigt
