### ISSUE TITLE
Reminder an Praktikanten

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#468]

**Comment by msollberger** [comment]
Für alle Praktikanten in ZEP.
MEGA möge allen Praktikanten einen Reminder betreffend der Arbeitsstunden schicken. Der Zeitsaldo aller Praktikanten soll spätestens am letzten Arbeitstag auf 0 h stehen. Weder Minus- noch Plusstunden sollen stehen bleiben.
