### ISSUE TITLE
Fehler beim Öffnen von Office Management

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#476]
Zeitpunkt 2021/09/08 ca 7 Uhr

Mein MEGA war offen (wenige Minuten - Session war aber noch aktiv), anschließender Klick auf "Office Management". Fehler:
![image](https://user-images.githubusercontent.com/16414159/128662067-1b188cf2-9248-4bb2-b2cb-19a2e86fa861.png)

Ein zweiter Klick war notwendig, um dann in die OM-Maske zu kommen.

Soll:
beim ersten Klick soll kein Fehler passieren

**Comment by patholzer** [comment]
Lässt sich nach derzeitigen Stand leider nichts unternehmen. Die Prod-Logs sind aufgrund eines neuen Pods nicht mehr vorhanden. Das Problem können wir sicher mit dem ELK-Stack zukünftig lösen (evtl. ist der durch gepaPLEXX bereits out of the box dabei). Der Fehler ist auch nicht reproduzierbar

@WernerBruckmueller Schließen wir das Ticket und öffnen es ggf. zu einem späteren Zeitpunkt wieder?
