### ISSUE TITLE
Summe an Stunden pro Projekt anzeigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#478]
Die PM-Ansicht soll erweitert werden, dass die Summe an geleisteten Stunden angezeigt werden.

Ist: es werden nur die MA-Stunden im Projekt angezeigt
Soll: Es soll auch die Summe (n.fakt/fakt) pro Projekt angezeigt werden

**Comment by WernerBruckmueller** [comment]
duplicate #486

**Comment by Ruhsi** [comment]
@WernerBruckmueller  UI-mäßig so OK?

![Bildschirmfoto 2021-11-19 um 07 44 51](https://user-images.githubusercontent.com/24733670/142577641-7907a4fb-16c6-4c88-b1c6-bae3d4f82efa.png)

**Comment by Ruhsi** [comment]
@WernerBruckmueller 
Fett:
![Bildschirmfoto 2021-11-30 um 08 14 53](https://user-images.githubusercontent.com/24733670/144002523-c9360cec-1e6c-4e1e-bf51-4c53eaec4db1.png)

Fett und unterstrichen:
![Bildschirmfoto 2021-11-30 um 08 15 30](https://user-images.githubusercontent.com/24733670/144002531-cbc72e24-eab9-44d2-9695-ea4ef81ae3d4.png)

Unterstrichen:
![Bildschirmfoto 2021-11-30 um 08 15 45](https://user-images.githubusercontent.com/24733670/144002537-4ae4a97f-5dc4-43a4-a4f6-439212fd4618.png)

**Comment by WernerBruckmueller** [comment]
Variante FETT
