### ISSUE TITLE
Adapt popup message

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#480]
Alle Texte kontrollieren und anpassen, wo Evelyn oder GF vorkommt.

Beispiel, hier gehört der Text durch HR ersetzt:

![image](https://user-images.githubusercontent.com/16414159/139798817-cf8d8965-50df-420d-95dd-87750dd9bc28.png)

**Comment by andreas-repo** [comment]
![aenderung_mega](https://user-images.githubusercontent.com/60095928/140023166-ac08957f-d13e-4b08-8606-b14d3817eb8f.PNG)

**Comment by WernerBruckmueller** [comment]
kenne den hintergrund nicht. Bzw wundert es mich, dass im code eine mail ist.

sollte mE nicht vorgekommen, garade da der code frei verfügbar auf github liegt.


@Ruhsi

**Comment by andreas-repo** [comment]
@WernerBruckmueller @Ruhsi 
Befindet sich in CommentResourceTest.java, dort liegen auch andere email Adressen wie zB.: 
"marko.gattringer@gmx.at", "marko.gattringer@gepardec.com" und "thomas.herzog@gpeardec.com"
