### ISSUE TITLE
Performance Probleme

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#482]
Siehe auch #410

- Erfassen von Kommentare dauert 5-10 sekunden. Für UX sehr schlecht. Man sieht bereits das Kommentar, aber es lädt und lädt, ...

**Comment by simonbauer-gepardec** [comment]
Ticket wird nun für folgendes Problem verwendet:

Nachdem man eine Anmerkung ändern / hinzufügt / löscht, werden im Hintergrund alle Projekte (PmEntries) neu geladen, das sieht man dadurch, das das Skeleton sichtbar wird (Skeleton = Graue Streifen, symbolisieren eine Ladevorgang). Dies ist zu Beginn performant, wird aber mit der Zeit sehr langsam, wenn der Cache voll wird. (Lokal hat es ein paar Sekunden gedauert).

Lösung: Nur noch Projekt neu laden, dessen Anmerkungen gerade bearbeitet wurden.
