### ISSUE TITLE
Bug: Mitarbeiterüberprüfung wird falsch angezeigt

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#497]
In der OM-View sind bei der Mitarbeiter Überprüfung alle Projekte grün, wo ich nicht Projektleiter bin.
Soll: nur die Projekte wo die Mitarbeiter Überprüfung erfolgreich war, soll angezeigt werden

![image](https://user-images.githubusercontent.com/16414159/144185243-acda7d9a-18f0-4108-871f-cc5cb7699f12.png)

**Comment by WernerBruckmueller** [comment]
@Ruhsi Hier handelt es sich um ein Frontendproblem. Werdet ihr es im Zuge von 3.1 beheben?

**Comment by Ruhsi** [comment]
Das hatte ich mir mit @Ollitod schon mal kurz angeschaut. Ist ein etwas aufwändigeres Thema. Ist eigentlich nicht im Scope von MEGA 3.1. Wenn es wichtig ist können wirs aber wsl am Ende von MEGA 3.1 reinzwicken, da ist eh Bugfixing geplant soweit noch Zeit bleibt.

**Comment by WernerBruckmueller** [comment]
Danke für's Update!
Die Ziele von 3.1 sollen dadurch nicht gefährdet werden.

**Comment by WernerBruckmueller** [comment]
Es soll das Flag "Überprüfung" aus der PM-View zur anzeige verwendet werden.
MA Check ist unabhängig.
