### ISSUE TITLE
Upgrade Quarkus 2.6.0

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#519]
Weiters werden alle Third-Party Dependencies upgegraded

Intellij bietet hierfür eine eigene Unterstützung, siehe
--> Views > Tool Windows > Dependencies 
Sofern das Tool verwendet wird, soll dem Team kommuniziert werden, wie gut/schlecht/... das Feature funktioniert 

Alle aufgrund der Quarkus-Version deaktivierten Tests müssen wieder laufen

**Comment by johannesr124** [comment]
Am Ende nochmal überprüfen:
- com.sun.xml.ws.rt neueste Version 3.0.2
