### ISSUE TITLE
Send reminders to OM

### ISSUE THREAD

**Issue by WernerGepardec** [Gepardec/mega#53]
As OM I want to get a reminder for the OM specific tasks. 

Precondition
Role OM as described in issue #57 is set up

The system shall send reminders for:
- [x] reminder to check user content (3. working day)
- [x] reminder to do the "Freigabe" (8. working day)
- [x] reminder for "Lohnverrechnung" (15. working day)
- [x] reminder for "Löhne" (-3 working day of the next month (e.g. 28.))

**Comment by mbrandm** [comment]
@WernerGepardec: what classifies an OM in ZEP? or is it a specific person?

**Comment by WernerGepardec** [comment]
@mbrandm the OM must be specified in MEGA. See #57

**Comment by mbrandm** [comment]
done, om can be defined via property-file
