### ISSUE TITLE
Regelarbeitszeit überprüfen

### ISSUE THREAD

**Issue by Ruhsi** [Gepardec/mega#548]

**Comment by Ruhsi** [comment]
Robin hat zb. Mittwochs 0 Stunden Regelarbeitszeit. In MEGA wird ihm ohne Buchung ein Fehler angezeigt.

![image](https://user-images.githubusercontent.com/24733670/151963056-d34f630d-4f35-4c84-ad22-932a01c610bd.png)

**Comment by WernerBruckmueller** [comment]
duplicate
