### ISSUE TITLE
Regelarbeitszeit mit 0h wird nicht erkannt

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#549]
Robin hat auch am Mittwoch 0h Regelarbeitszeit (zumindest in der Prod). Das wird aktuell in MEGA noch nicht berücksichtigt und er bekommt einen Fehler.

![image](https://user-images.githubusercontent.com/16414159/151963390-9bd3670e-97c2-4755-8e3b-cf937d550ade.png)

Betrifft auch andere MA

**Comment by WernerBruckmueller** [comment]
Siehe #547

**Comment by WernerBruckmueller** [comment]
Bei der Regelarbeitszeit wird das von und bis-Datum nicht berücksichtigt:
![image](https://user-images.githubusercontent.com/16414159/186346019-d61576df-e9d3-440e-b860-a938e39727a1.png)

**Comment by LeitnerMi** [comment]
Derzeit wird nur das letzte Datum berücksichtigt.

Beim Syncen des Employees werden die RegularWorkingHours zu diesem dazu gespeichert und daher kann man immoment nicht mit dem ausgewähltem Datum aus dem Frontend auf ältere Daten zugreifen.

**Comment by WernerBruckmueller** [comment]
Folgeissue: #615
