### ISSUE TITLE
New Employee - 500 Internal Server Error

### ISSUE THREAD

**Issue by fwagner94** [Gepardec/mega#561]
**Describe the bug**
As a new employee (in the first month) I get an error 500 after login with google. 

**To Reproduce**
1. Go to login page
2. Click on 'Login'
3. See error 'Ein Fehler ist aufgetreten: Http failure response for https://mega-zep-backend-57-mega-prod.cloud.itandtel.at/worker/monthendreports: 500 Internal Server Error'

**Expected behavior**
As there is maybe no data to show, I expect an empty sheet or something.

**Screenshots**
![error500](https://user-images.githubusercontent.com/100685830/156985413-e1729baf-a4cc-40ac-83e2-2bed9e0db4c5.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey (12.2.1)
 - Browser chrome
 - Version 99.0.4844.51

**Comment by WernerBruckmueller** [comment]
Fehler passiert, wenn das Freigabedatum nicht gesetzt ist.

**Comment by WernerBruckmueller** [comment]
Vorschlag: Falls das Freigabedatum nicht gesetzt ist, soll das Eintrittsdatum verwendet werden

**Comment by WernerBruckmueller** [comment]
Simulation mittels Freigabedatum zurücksetzen erfolgreich
