### ISSUE TITLE
Fehltage bei Karenz (und anderen Abwesenheiten) ignorieren

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#570]
Alle gültigen Abwesenheiten sollen erkannt werden (siehe auch #569)

**Comment by Ruhsi** [comment]
Backend ist fertig und gemerged. Frontend-Teil fehlt noch.

**Comment by WernerBruckmueller** [comment]
@andreas-repo Was passiert, wenn man eine Buchung trotz Fehlzeit hat? Bzw eine Fehlbuchung (zB kein Mittag). Wird das überprüft?
