### ISSUE TITLE
Problem mit @Transactional bei Tests oder Applikation

### ISSUE THREAD

**Issue by andreas-repo** [Gepardec/mega#575]
Wenn bei der Klasse UserRepository ein @Transactional zur Klasse hinzugefügt wird funktionieren die Tests aber die Applikation wirft einen Fehler beim Aufruf von MEGA.

Wird @Transactional von der Klasse entfernt schlagen die Tests fehl aber die Applikation startet wieder normal.

Siehe [Transactional-Fehlerausgabe.txt](https://github.com/Gepardec/mega/files/8529868/Transactional-Fehlerausgabe.txt) für die Fehlerausgabe wenn @Transactional zu UserRepository-Klasse hinzugefügt wurde.

**Comment by andreas-repo** [comment]
wurde gelöst

**Comment by WernerBruckmueller** [comment]
@Ruhsi kann ich das testen?

**Comment by Ruhsi** [comment]
@WernerBruckmueller nicht wirklich. Solange beim Testen keine Transaktionsfehler auftreten, passt das. Repository-Tests laufen durch
