### ISSUE TITLE
Urlaub wird falsch berechnet

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#585]
Im September ist der ganze Monat mit eine Fehlzeit (Karenz) belegt. Es ist jedoch ein Urlaub von 3 Tagen ersichtlich.
![image](https://user-images.githubusercontent.com/16414159/167376887-b699fc5e-c199-4b5b-8fd2-4c2c2ed833b9.png)

**Comment by Ruhsi** [comment]
@WernerBruckmueller du hast laut ZEP im Dezember 3 Tage Urlaub eingetragen und der Rest ist Karenz. Die 3 Tage Urlaub werden auch angezeigt. Sollen in dem Fall die Karenztage zu den Urlaubstagen hinzugezählt werden?
![Bildschirmfoto 2022-05-13 um 11 34 42](https://user-images.githubusercontent.com/24733670/168255953-92faff21-b54d-43a4-a937-092197f80772.png)

**Comment by WernerBruckmueller** [comment]
ich verstehe nicht, warum es einmal als urlaub angezeigt wird (also durch personio).
MEGA macht offensichtlich das richtig.
