### ISSUE TITLE
Zusätzliche Daten eines MAs anzeigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#599]
In eigenem Bereich im Dashboard:
- Aktuelle Überstunden
- Urlaubstage
--> Darstellung noch offen

Sofern dies aus ZEP möglich ist.

Siehe #657 und #664

**Comment by WernerBruckmueller** [comment]
Über die ZEP-Schnittstelle werden diese Daten (noch?) nicht angeboten. Somit wird dieses Issue nach hinten gereiht.
Evtl können die Daten über Personio aufgerufen werden (Schnittstelle ist nicht eingebunden).

**Comment by WernerBruckmueller** [comment]
Hinweis: Datenhoheit über den Urlaub hat Personio. In ZEP kann dieser abweichen.

**Comment by WernerBruckmueller** [comment]
Aus aktueller Sicht wird in der nächsten ZEP-Release die SOAP Schnittstelle um die Überstunden aktualisiert.
Die Urlaubstage können für uns nicht aus ZEP übernommen werden (siehe voriges Kommentar).

**Comment by Ollitod** [comment]
@WernerBruckmueller das Issue hab ich noch nie gesehen. Wusste nicht, dass da von ZEP noch gar keine Information zu dem Überstundensaldo verfügbar ist und du da (laut letztem Kommentar) schon Infos zu einer neuen Version hast. Gibt es dazu nun schon Neuigkeiten, ob mit einer neuen Schnittstellenversion diese Informationen abgefragt werden können?

**Comment by WernerBruckmueller** [comment]
Dieses Issue wurde in #664 und #603 aufgeteilt. Darin sind auch die aktuellen Infos zu finden.

Ich werde das Issue schließen. DIe aktuellsten Infos sind in den beiden Issues festgehalten. Sollten noch etwas offen sein, bitte um Klärung per Chat/Telefon.
