### ISSUE TITLE
Vorvormonat lässt sich nicht bestätigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#602]
![image](https://user-images.githubusercontent.com/16414159/182082542-e578e9d0-7866-40c5-8b69-5662b7351f02.png)

Die Warnung ist korrekt, dass eine Buchung außerhalb der Soll-Arbeitszeit ist.

Es ist jedoch nicht möglich, die Zeit zu bestätigen. Die Seite wird lediglich aktualisiert.

Freigabedatum: 2022-05-31
Datum: 1. August (Juli soll bestätigt werden)

**Comment by WernerBruckmueller** [comment]
Das Freigabedatum wurde auf Ende Juni gesetzt, dann konnte die Buchung erfolgreich gemacht werden. Obwohl zuvor auch Juli ausgewählt war.

**Comment by WernerBruckmueller** [comment]
Vermutlich kann das Issue mit #601 gelöst werden

**Comment by simonbauer-gepardec** [comment]
Wird durch #601 gelöst, daher [CLOSE]
