### ISSUE TITLE
OM "Monatsabschluss in ZEP durchführen auch in DB entfernen" 

### ISSUE THREAD

**Issue by LeitnerMi** [Gepardec/mega#605]
Siehe #596:

"Unter 'Unternehmen" wird "Monatsabschluss in ZEP durchführen' nicht verwendet. Diese soll entfernt werden."

Jegliche Code-Implementation wurde schon entfernt. Nun muss nur noch das Datenbankschema angepasst werden. Dies sollte jediglich ein Flag im Enterprise-Entry sein.

Datenbank --> Table: enterprise_entry, Column: set_monthly_report_done

**Comment by Ollitod** [comment]
Another unused Step named ACCEPT_TIMES is obsolet as well and will therefore be removed.
