### ISSUE TITLE
Dashboard Cards vertauschen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#611]
Zeiten- und Resie-Check sollen auf der linken Seite dargestellt werden.
Die Monatsinfo ist rechts darzustellen.

![image](https://user-images.githubusercontent.com/16414159/186340044-c70fc497-0b96-403c-8289-85c99f6fa5da.png)

**Comment by LeitnerMi** [comment]
Will be finished with #612. Issue doesn't have his own feature branch.
