### ISSUE TITLE
Schnelleinstieg in das ZEP-Projekt

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#614]
Wenn man in der OM-View auf das jeweilige Projekt klickt, so soll man direkt in das ZEP-Projekt einsteiegen können.

Aktuell ist dies auch bei den Mitarbeitern umgesetzt.

**Comment by simonbauer-gepardec** [comment]
Wenn aus irgendeinem Grund, keine ZepId für ein Projekt hinterlegt ist (Datenbank Fehlstand, Zeitraum zwischen Einsatz in der Prod und nächsten Projekt-Sync etc,,,) wird folgender Tooltip angezeigt:
![image](https://user-images.githubusercontent.com/108525722/221862491-4f02ff56-a16b-4134-8928-9593f5a3ecd9.png)
