### ISSUE TITLE
Mega-Dash nimmt Freigabedatum für EmployeeCheck

### ISSUE THREAD

**Issue by LeitnerMi** [Gepardec/mega#616]
Karte in der Mitte (Employee-Check) nimmt Freigabedatum für BottomSheet und für das Bestätigen der Zeiten. 

Das Icon in der Mitte wird jedoch anhand des auswählbaren Datum geändert. Das restliche Mega-Dash wird mittlerweile auch durch das auswählbare Datum geändert.

Der Zeiten-Check soll nun auch nicht mehr an das Freigabe-Datum gebunden sein, sodass man auch Zeiten in der Vergangenheit bestätigen kann und auch den Status der Vergangenheit prüfen kann.

**Comment by simonbauer-gepardec** [comment]
Der Zeiten-Checkist durch #601 nicht mehr an das FreigabeDatum gebunden, daher [CLOSE]
