### ISSUE TITLE
MEGA-Dash: Kontrolle der Zeiten-Status nicht ok

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#626]
Im Dashboard werden PL angezeigt, welche keine offene Aufgaben bei mir haben:
![image](https://user-images.githubusercontent.com/16414159/194808389-5c958d17-c0e3-40a9-b4cf-f1929273db75.png)

Der obere PL kann keine Zeiten von mir zu bestätigen (wurde bei ihm in der PL-Ansicht überprüft).

Details sind in einem Call zu klären.

**Comment by WernerBruckmueller** [comment]
Vermutlich ist hier der selbe / ähnliche Fehler:
![image](https://user-images.githubusercontent.com/16414159/198286075-36715b48-4386-4571-8467-22d361bd8ecf.png)

**Comment by WernerBruckmueller** [comment]
Noch relevant?

**Comment by WernerBruckmueller** [comment]
Siehe #675

**Comment by WernerBruckmueller** [comment]
Es wird der falsche Monat im MA-Dashboard beim PM-Popup angezeigt.

Wird das Dashboard geöffnet, ist September ausgewählt. Im PM-Popup wird kein PM dargestellt. Vermutlich wird ein falscher Monat dargestellt.

September wird in der PM Maske bestätigt --> wenn man im MA-Dashboard August auswählt sieht man die korrekten PM-Bestätigungen.

**Comment by Ollitod** [comment]
Fix behebt auch das "springende" Bottom-Sheet in der Mitarbeitertabelle der Office-Management Ansicht

**Comment by WernerBruckmueller** [comment]
Test erfolgreich
