### ISSUE TITLE
Zeit für Mail anpassen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#627]
Die Verständigungsmails sollen um 7 Uhr beim Benutzer ankommen.

Der Scheduler für den Versand, verwendet die Zeit vom Cluster, welcher eine andere Zeit konfiguriert hat.

Es ist mit gepaPLEXX abzustimmen, ob die Zeit bei der MEGA-Config oder auf der Umgebung anzupassen ist.

**Comment by Ruhsi** [comment]
@WernerBruckmueller @gattma Zeit im Container ist auf 'Europe/Vienna' konfiguriert. Log-Uhrzeiten sind nun auch richtig.
ist auf prod deployt
