### ISSUE TITLE
Neuer MA kann keine Zeiten bestätigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#628]
Ein neuer MA konnte heute keine Zeiten bestätigen. Nachdem das Freigabe Datum auf Ende September gesetzt wurde, hat es funktioniert.

**Comment by WernerBruckmueller** [comment]
Testnachstellung: Freigabedatum auf NULL stellen.
Im MEGA-Dashoard zeit bestätigen, dann sollte ein fehler kommen

**Comment by simonbauer-gepardec** [comment]
Problem konnte ich nicht auf der Testzone nachstellen. Mein ReleaseDate wurde in ZEP auf null gestellt. Es gibt jedoch im Backend einen Code, der in diesem Falle dann das created-Date (aus ZEP) für das releaseDate her nimmt. Somit war mein ReleaseDate beim Zeiten bestätigen doch nicht NULL und es hat funktioniert.

ReleaseDate wird mit https://github.com/Gepardec/mega/issues/601 sowieso nicht mehr beim Buchungen bestätigt verwendet. Daher [CLOSE]
