### ISSUE TITLE
Link für Planrechnung aktualisieren (zum Jahreswechsel)

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#635]
Gewünschter Produktivgang zwischen Mitte Jänner und Ende Jänner.

Neuer Link: https://docs.google.com/spreadsheets/d/1mmc1pvhr1Z_IbiMELtM98mFZ4-2uuSx6Sg_uZXRNpH0/

**Comment by WernerBruckmueller** [comment]
@Ollitod @Ruhsi könnt ihr die url bitte anfang 2023 austauschen?

**Comment by Ruhsi** [comment]
@WernerBruckmueller ich bin bis 9. Jänner im Urlaub, danach kann ich das ändern

**Comment by Ruhsi** [comment]
@WernerBruckmueller ist auf main, environment/test UND *environment/prod* deployt.
Hab die URL aktualisiert, anstatt auszubauen. Hoffe das passt :)
