### ISSUE TITLE
Austrittsdatum bei Projekt korrekt berücksichtigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#644]
Ist das Austrittsdatum eines MAs mit Ende Jänner, so ist dieser in MEGA beim Projekt für den Monatsabschluss Jänner (also im Februar) nicht ersichtlich.
Für die PL-Kontrolle ist das jedoch notwendig.

**Comment by simonbauer-gepardec** [comment]
Testuser:
Clemens K. in projekt L-ALLG
Buchung im Jänner
Austrittsdatum / Beschäftigungszeitraum : Bis Ende Jänner.

IST:
Wird im Jänner bei ProjektMgmt nicht angezeigt

SOLL:
Wird im Jänner bei ProjektMgmt angezeigt.

**Comment by WernerBruckmueller** [comment]
Sehe Clemens im besagten Projekt nicht im Jänner oder Februar. Evtl sind die Steps neu zu generieren.

**Comment by WernerBruckmueller** [comment]
Was bewerikt die Umsetzung? User sehe ich nicht.

**Comment by WernerBruckmueller** [comment]
test ok

**Comment by WernerBruckmueller** [comment]
Hinweis: Es werden nur MAs berücksichtig welche bis zum Monatsletzten eingestellt sind.
