### ISSUE TITLE
PM-View: Offene Projekte (alphabetisch) oben anzeigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#645]
Ansicht Projekt Management
- Aktuell wird rein alphabetisch sortiert
Soll:
- Alphabetisch
- Projekte im Status: In Abreit und Offen (Projektcontrolling + Rechnungslegung) sollen oben sein (auch alphabetisch)
- Projekte mit noch nicht überprüften MAs sollen oben sein
- Projekte mit dem Status "nicht relevant" sollen sich wie "Fertig" verhalten

**Comment by WernerBruckmueller** [comment]
![image](https://user-images.githubusercontent.com/16414159/219601111-68c3a9ce-6c5c-415a-b50e-a0e540e31cb1.png)

**Comment by Ollitod** [comment]
Folgendes wurde im Zuge dieses Issues ebenfalls umgesetzt @WernerBruckmueller:

- Anmerkungen in der OM/PM-View können wieder bearbeitet und gelöscht werden
- Wenn in der PM-View Mitarbeiter über die Checkboxes selektiert werden und danach der Button "Überprüft" geklickt wird, dann werden die Checkboxes automatisch zurückgesetzt, sobald die Daten aktualisiert wurden
