### ISSUE TITLE
Endlosschleife nach Aktualisierung des Freigabedatums

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#646]
IST:
Wird das Freigabedatum über den "Freigeben"-Button aktualisiert, dann werden die Mitarbeiter neu geladen und dabei entsteht eine Endlosschleife.

SOLL:
Mitarbeiter werden erfolgreich neu geladen und angezeigt.

**Comment by WernerBruckmueller** [comment]
Test fehlgeschlagen
