### ISSUE TITLE
Erledigte Anmerkung in "Mein MEGA" nicht sichtbar.

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#648]
Ich habe am 13.3 ein MA-Kommentar für Dezember vergeben. Dieses ist überall sichtbar - ok.
Sobald ich es erledigt habe, ist es in keinem Monat mehr sichtbar - nicht ok.
Das erledigte Kommentar soll auch im jeweiligen Monat sichtbar sein.

**Comment by simonbauer-gepardec** [comment]
Mit diesem Issue wird zusätzlich folgendes behoben:

Das "grüne Icon" auf dem Dashboard (Alles wurde erledigt etc...) funktioniert nicht richtig.
Es wird angezeigt, wenn mein Status auf Done ist und die Variable "otherChecksDone" vom Backend auch true ist.
Die Ermittlung von otherChecksDone hat überhaupt nicht funktioniert.

Es wurden alle StepEntries, wo ich der Owner bin, ab dem RELEASE_DATE+1_Monat von mir abgefragt. Dann wurde überprüft, ob alle auf DONE sind.
Der erste Fehler ist schon mal, dass nach dem RELEASE_DATE+1_Monat selektiert wird. Es soll der aktuell ausgewählte Monat sein.
Der 2. Fehler, der sich hier eingeschlichen hat: Letzten Sommer wurden 2 Steps entfernt (zumindest die Business Logik davon). Diese Steps werden aber noch generiert. Diese müssen hier ebenfalls ignoriert werden und im besten Fall sollen sie erst gar nicht mehr generiert werden, das ist aber ein anderers Thema
