### ISSUE TITLE
Bestätigen Buttons werden angezeigt, obwohl das Monat nicht verfügbar ist

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#651]
**IST:**
Wählt man im Tab "Mein MEGA" rechts oben ein Datum aus, wo es keinen korrespondierenden StepEntry dazu in der Datenbank gibt, werden die Buttons "Buchungen bestätigen" und "Bestätigen noch nicht möglich, weil..." angezeigt.

**SOLL:**
Oben genannte Buttons dürfen nicht angezeigt werden, da etwaige Benutzereingaben nicht persistiert werden können.

**Comment by WernerBruckmueller** [comment]
Wurde mit Minor bewertet, da diese Konstellation nur in einer Testumgebung auftreten kann.
