### ISSUE TITLE
Avatar-Icon wieder im Frontend aktivieren

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#653]
Vorrübergehender Fix von #652 ist wieder auszubauen, sobald KeyCloak mit der Bezeichnungs-Länge von Avatar-Bildern umgehen kann

**Comment by simonbauer-gepardec** [comment]
Ist quasi durch https://github.com/Gepardec/mega/issues/652 erledigt / mitgedacht.
Sobald das Profilbild wieder aktiviert ist, wird es automatisch in der GUI angezeigt.
