### ISSUE TITLE
Enum WorkingLocation überarbeiten

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#655]
**IST:**
Die Enumeration **WorkingLocation** ist ein Abbild des Dropdown-Menüs "Arbeitsort" in ZEP.
Wenn in ZEP ein neuer Arbeitsort hinzugefügt wird, muss dieser manuell in der Enumeration nachgezogen werden.

**SOLL:**
Für etwaige Checks durch MEGA, sind prinzipiell nur die Werte _MAIN_ und _AT_ relevant. Alle anderen Arbeitsorte können "as is"  von der ZEP-Schnittstelle von MEGA verarbeitet werden, ohne diesen Arbeitsort explizit in der Enumeration **WorkingLocation** zu führen.

**Technisch:**
Vor Umsetzung kurze Besprechung mit @Ruhsi oder @Ollitod , wie die Lösung konkret aussehen soll.
Denkbar wäre eine Verwaltung in der Datenbank, um die Arbeitsorte einfach anpassbar zu machen oder für alle ausländischen Arbeitsorte eine Überkategorie zu schaffen, auf die alle ausländischen Arbeitsorte automatisch gemapped werden.

**Comment by rainer-gepardec** [comment]
Würde sich eigentlich auch anbieten, dass man das im Environment konfigurierbar macht und mit einem Rollout ausrollt. Soweit ich weiß gibts für die MEGA-Datenbank ja keine Schnittstellen sondern "nur" Scheduled-Jobs.

**Comment by Ollitod** [comment]
> Würde sich eigentlich auch anbieten, dass man das im Environment konfigurierbar macht und mit einem Rollout ausrollt. Soweit ich weiß gibts für die MEGA-Datenbank ja keine Schnittstellen sondern "nur" Scheduled-Jobs.

Das wäre auch eine Möglichkeit, aber dort sollte doch eher die umgebungsspezifische Config rein, oder?
