### ISSUE TITLE
Überstunden von einem Monat anzeigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#657]
---
Überstunden von einem Monat anzeigen
---

1. **What is the current state?**

Es wird keine Statistik bezüglich der Überstunden in einem Monat angezeigt.

2. **What is the desired state?**

Um seinen Monat besser planen zu können, soll in der Monatsinfo ein neuer Eintrag mit den +/- Überstunden erstellt werden. Dabei sollen geplante Fehlgründe (ZA, Urlaub, Arzt) miteinbezogen werden.

3. **Screenshots**

![Screenshot 2023-11-13 at 11-18-09 MEGA](https://github.com/Gepardec/mega/assets/87299303/50c7d63e-5e24-4311-8c56-0d45a62ef0fa)

4. **Ähnliche Issues**

siehe #703

**Comment by WernerBruckmueller** [comment]
Umsetzung im Dashboard:
- Überstanden zu einem Stichtag (zum Monatsletzten) anzeigen. Grenzzeiten (+/-) fett und rot hervorheben, wenn diese über/unterschritten werden.

Popup bei 15 Minusstunden.

Ausnahmen: Externe MAs, GF, ...

**Comment by Ollitod** [comment]
@LeitnerMi es muss auch noch das Überstunden-Saldo angezeigt werden. Die angezeigt Info ist zwar auch nützlich (angefallene Über-/Minusstunden im ausgewählten Monat), allerdings zielt das Issue hauptsächlich darauf ab, einen Einblick in den aktuellen "Kontostand" per Stichtag zu bekommen (z.B. Monatsletzter des ausgewählten Monats).

**Comment by LeitnerMi** [comment]
@Ollitod Soweit ich aus dem Ticket #599 entnehmen kann, ist eine solche Abfrage noch nicht in ZEP/Personio verfügbar. Aufgrund der grundlegenden monatlichen Strukturen kann man ohne großen Umbau keine monatsübergreifenden Statistiken berechnen.

Mein Plan: Ich erstelle ein neues Ticket, in welches ich diesen Thread übernehmen werde und schließe dieses, oder verlagere diesen Thread in #599 . Akzeptiert, anderer Vorschlag?

**Comment by WernerBruckmueller** [comment]
Bitte mit @ViktoriaWip abstimmen, ob die Anforderung sinnvoll ist.

Wenn geplante Fehlgründe (ZA, Urlaub, Krank) im Personio eingetragen wurden, sollen diese nicht berücksichtigt werden.

**Comment by WernerBruckmueller** [comment]
Test mit negativen Stunden auf der Testumgebung war erfolgreich.
