### ISSUE TITLE
Wording im Dashboard anpassen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#665]
Das Wording im Dashboard soll überarbeitet werden, damit es klarer ist:
![image](https://github.com/Gepardec/mega/assets/16414159/3849f41e-27c0-4c7b-9b49-185ab6a69fa7)

@msollberger bitte Wording-Vorschlag bis Ende Juni in diesem Issue einarbeiten.

**Comment by msollberger** [comment]
Neues Wording:

Urlaub ==> Konsumierter Urlaub
Zeitausgleich ==> Konsumierter Zeitausgleich X Stunden (Tage)
Homeoffice ==> Homeoffice (fällt mir nix besseres ein)
Krankenstand ==> Krankenstand (fällt mir nix besseres ein)

**Comment by WernerBruckmueller** [comment]
Neues Wording bei der linken Spalte:

Urlaub ==> Konsumierter Urlaub
Zeitausgleich ==> Konsumierter Zeitausgleich
