### ISSUE TITLE
Fahrzeug-Enum anpassen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#666]
In ZEP wude ein neues Fahrzeug hinzugefügt: 
Vehicle 'Firmenauto' is not mapped in Enum Vehicle

Bitte ASAP ergänzen und hinzufügen.

**Comment by WernerBruckmueller** [comment]
Errorhandling ist auch anzupassen. ggf Enum austauschen

**Comment by Ollitod** [comment]
Neuer Fahrzeugtyp wird wieder aus ZEP gelöscht. Issue ist somit obsolet
