### ISSUE TITLE
PostgreSQL Container: V10 not supported

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#669]
The documentation (README) contains a command for creating a database container based on the postgres image in version 10.
According to @PaulProemer (thanks for noticing ;)) this version is not supported anymore.

TODOs:

- update the documentation to use a newer postgres version which is supported (preferably the latest stable version)
- check if the production containers use postgres in version 10 as well and upgrade them as well (check repository mega-backend-ci or get in touch with @fhochleitner or @gattma)

**Comment by fhochleitner** [comment]
mega currently uses postgres v12.5.x
