### ISSUE TITLE
Belege aus ZEP darstellen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#674]
Im MA-Dashboard sollen die Belege im Dashboard ersichtlich sein, sofern es welche im angegeben Monat geben.

In der Darstellung, sollen zumindest folgende Daten enthalten sein:
- Datum
- Projektname
- Betrag Brutto
- Zahlung Firma/privat
- Belegart
- - Ist Anhang dabei? Evtl gleich verlinken.

Mögliche Lösungsidee:
- über einen Button werden die Belege geöffnet und können bestätigt werden. Anschließend lönnen erst die Zeiten kontrolliert werden. DIese Idee ist ggf mit einem UX-Experten abzustimmen.
- 
Siehe #696

**Comment by Ollitod** [comment]
@WernerBruckmueller bitte mal soweit analysieren, welche Daten abgefragt werden sollen, ohne die Darstellung zu berücksichtigen, da wir das im aktuellen Frontend nicht mehr umsetzen werden.

**Comment by gattrCh** [comment]
Backend done - Frontend in dev

**Comment by WernerBruckmueller** [comment]
@ViktoriaWip soll eine Warnung angezeigt werden, wenn kein Dokument beim Beleg hochgeladen ist? Aus meiner Sicht schon.

**Comment by WernerBruckmueller** [comment]
@gattrCh bitte als Titel "ZEP-Belege" verwenden
