### ISSUE TITLE
Buchungen automatisch bestätigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#699]
1. **What is the current state?**
 - Aktuell kann ein MA die Zeiten und Buchungen mit einem Klick im Dashboard bestätigen. 
 - Wenn ein MA über ein gesamtes Monat abwesend ist (zB Krank/Urlaub/Karenz/... ), so kann dieser den Monat nicht bestätigen.

2. **What is the desired state?**
- Sind in einem Monat keine Zeitbuchungen erfolgt und für **alle** Arbeitstage eine Abwesenheit (ZA/Urlaub/Krankenstand/Karenz/...) eingetragen, so wird automatisch der Monat als Bestätigt markiert (zum Monatswechsel).
- Dies betrifft nur interne Mitarbeiter mit entsprechender Soll-Arbeitszeit.

- AC3: Ungebuchte Monate mit Abwesenheit werden automatisch durch MEGA bestätigt, mit Monatswechsel.

Siehe Issue #684

**Comment by gattrCh** [comment]
in dev again - because of changes
