### ISSUE TITLE
Über ZEP versendete Emails in MEGA als Kommentar hinzufügen

### ISSUE THREAD

**Issue by Ollitod** [Gepardec/mega#702]
1. **What is the current state?**
Die Kontrolle der gebuchten Zeiten durch OM/PM erfolgt über ZEP. Wenn bei einer Buchung ein Fehler bemerkt wird, muss man in MEGA ein Kommentar für den betroffenen MA erfassen und viele Informationen zu der betroffenen Buchung manuell ergänzen, was oftmals mehr Zeit in Anspruch nimmt, als den Fehler in der Rolle als OM/PM direkt auszubessern.

- What were the necessary steps to achieve this state?
  - [Feature]: How is this handled currently? (or not even possible?)
    - -> Goal of the feature
    - In ZEP gibt es die Möglichkeit, eine E-Mail Verständigung zu einer konkreten Buchung direkt von der Stelle aus zu versenden, von der aus die Kontrolle der gebuchten Zeiten durch OM/PM erfolgt und den Inhalt dieser Mail als Kommentar in MEGA zu speichern, damit der MA diese Aufgabe dann in MEGA einsehen und erledigen kann. Dazu ist es notwendig, die E-Mail, die versendet wird, im CC and die Service-Adresse von Gepardec zu senden, damit durch einen periodischen Task die Mailbox auf neue Nachrichten geprüft werden kann. 
    - **Technisch**:
         - Neue Spalte "source_system" in Tabelle "comment", per default befüllt mit "MEGA". Wenn das Kommentar aus einer E-Mail erzeugt wird, dann ist "ZEP" einzutragen.

2. **What is the desired state?**

- [Feature]:
  - -> Acceptance criteria
  - AC1: E-Mail Postfach des Service-Accounts wird alle 10 min auf neue relevante E-Mails geprüft.
  - AC2: MEGA versendet keine Benachrichtigung, wenn ein neues Kommentar von "ZEP" kommt, da der MA ohnehin ein E-Mail mit den relevanten Infos von ZEP bekommt.
  - AC3: MA, der die E-Mail versendet, wird per E-Mail benachrichtigt, wenn die E-Mail nicht als MEGA-Kommentar gespeichert werden kann (neues E-Mail Template erforderlich)
  - AC4: Auslesen der Mailbox ist per default deaktiviert und muss über eine ConfigProperty explizit aktiviert werden (neuer Eintrag in values.yaml)
  - AC5: E-Mail Adresse, von der aus die E-Mail verschickt wird, ist abhängig von der ZEP-Umgebung (neuer Eintrag in values.yaml)
  - AC6: Kommentar ist in MEGA beim Mitarbeiter ersichtlich

_=> Move issue to "backlog"_

**Comment by Ollitod** [comment]
Entwurf für E-Mail Benachrichtigung bei fehlerhafter Verarbeitung:
```
<p>Hallo <Vorname-Versender-ZEP>,</p>
<p>die von dir in ZEP versandte E-Mail an <b><Nachname, Vorname MA></b> konnte von MEGA nicht verarbeitet werden.</p>
<p>Grund: <Fehlertext></p>
<p>Bitte versuche, die E-Mail erneut über ZEP zu versenden oder nutze direkt die in MEGA integrierte Kommentarfunktion,
    um den Mitarbeiter über die fehlerhafte Buchung zu verständigen.</p>
<p>Sollte das Problem weiterhin bestehen, wende dich an das MEGA Entwicklungsteam.</p>
```

**Comment by Ollitod** [comment]
Entwurf für Inhalt Kommentar:
`Deine Buchung vom <Datum-Buchung> im Projekt '<Projekt>' weist beim Vorgang '<Vorgang>' von <Uhrzeit-von> bis <Uhrzeit-bis> (<Anuzahl Stunden> mit der Bemerkung '<Bemerkung>' einen Fehler auf. <Freitext aus E-Mail von Verfasser>`

**Comment by WernerBruckmueller** [comment]
Ergänzung: Mail-Receiver läuft alle 10 min zwischen 7 und 18 Uhr.

**Comment by WernerBruckmueller** [comment]
Frage: Wenn der MA keine Verständigung von MEGA bekommt (was mE auch Sinn macht), wenn die Nachricht schon per Mail verschickt wurde.
Wie weiß der MA jedoch dann, dass dieser in MEGA das Kommentar bestätigen muss, sobald es abgearbeitet wurde?
Evtl ist das Template anzupassen.

Was meint ihr @ViktoriaWip @Manuel-Vilim ?

**Comment by WernerBruckmueller** [comment]
@Ollitod Kommentare an Interne-Projekte sind nicht möglihc

**Comment by WernerBruckmueller** [comment]
Vorschlag für Template (Stammdaten -> Projektzeiten -> Mail Vorlagen -> Projektzeit-Details):

Betreff: Projektzeit %DATUM% von %VON% bis %BIS% (%STUNDEN% Stunden)
Inhalt: 
```
<p><p></p>
<p><br></p>
<p><br></p>
<p><br></p>
Hinweis: Kommentare sind in <a href="https://mega.gepardec.com/" target="_blank">MEGA </a>zu bestätigen.&nbsp;</p>
<p><p></p>
<p></p>
<p><font color="#9c9c94">#METADATEN####################################</font></p>
<p><font color="#9c9c94">Ersteller-ID: %I_USERID%<br>Mitarbeiter: %MITARBEITER%<br>Projekt: %PROJEKT%<br>Vorgang: %VORGANG%<br>Ticket: %TICKET%<br>Teilaufgabe: %TEILAUFGABE%<br>Tätigkeit: %TÄTIGKEIT%<br>Ort: %ORT%<br>Bemerkungen: %BEMERKUNGEN%</font></p>
<p></p>
</p>
```

**Comment by WernerBruckmueller** [comment]
Entwurf für Inhalt Kommentar:
Buchung vom <Datum-Buchung> (<Uhrzeit-von> - <Uhrzeit-bis>) mit dem Text '<Bemerkung>' ist anzupassen. 
<Freitext aus E-Mail von Verfasser>

Beispiel:
Buchung vom 18.10.2023 (08:00 - 08:15) im Projekt  'PRO1-Allgemein' - 'ABC_1' mit dem Text 'TEXT' ist anzupassen. 
Umbuchen auf Intern.

**Comment by WernerBruckmueller** [comment]
Bei der E-Mail Benachrichtigung bei fehlerhafter Verarbeitung, soll das Mail bzw der Inhalt angehängt werden, damit man weiß, was man geschrieben hat. 
Wichtig ist mir, dass klar ist, was man als Verfasser geschrieben hat. Lösung soll technisch einfach sein.
