### ISSUE TITLE
Überstunden anzeigen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#703]
What is the current state?
Aktuell kann der MA über ZEP bzw Persionio die Über-/Minusstunden ansehen. Dies soll komfortabler werden.
What is the desired state?
In der MA-Ansicht, sollen die aktuellen Über-/Minusstunden des jeweiligen MAs zu einem Stichtag angezeigt werden.
Die AC sollen gemeinsam definiert werden, da diese von der techn. Schnittstelle abhängig sind.
![image](https://github.com/Gepardec/mega/assets/16414159/582fcc0d-5419-4bf7-9213-34f95b9673db)

Umsetzung im Dashboard:

Überstanden zu einem Stichtag (zum Monatsletzten des Vormonats) anzeigen. Grenzzeiten (+/-) fett und rot hervorheben, wenn diese über/unterschritten werden.
Popup bei 15 Minusstunden.

Ausnahmen: Externe MAs, GF, ...

Es ist ein neuer Dashboard Bereich zu erstellen.

**Comment by Ollitod** [comment]
Wird nicht umgesetzt, da es keine direkte Schnittstelle gibt, um die Informationen zu erhalten.
