### ISSUE TITLE
Seite konnte nicht gelande werden

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/mega#712]

**Comment by ChrisKofler** [comment]
<img width="1303" alt="image" src="https://github.com/Gepardec/mega/assets/20546046/0ef0fa7d-7836-4059-bc78-a5b91b268ddf">

**Comment by Ollitod** [comment]
Der Fehler ist nicht reproduzierbar. Bitter erneut einmelden, sollte das Problem wieder auftreten.
