### ISSUE TITLE
Regex für Projekte bei MEGA aus ZEP

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#718]
1. **What is the current state?**
  - [Bug]:
Projekte, die eine Projektbeschreibung haben, werden nicht gefunden (weil die Projektbeschreibung? in der Klammer ist).

2. **What is the desired state?**

- [Bug]:
  - -> Projektzugehörigkeit soll gefunden werden. Alternativ dem Intern-Projekt zugewiesen werden.

**Comment by WernerBruckmueller** [comment]
Wenn jemand der ein Kommentar erstellt, einem Projekt nicht zugewiesen ist, so soll es ein Fallback auf Projekt-Intern geben.

**Comment by LeitnerMi** [comment]
Kontext: Der von mir gefundene Fehler war, dass NUR der Projektleiter einem Mitarbeiter in einem Projekt einen Kommentar erstellen konnte. Keine andere Person konnte einen Kommentar für den Mitarbeiter erstellen.

Technischer Hintegrund:
Beim Erstellen des Kommentars, wird nach dem zugehörigen StepEntry gesucht. Dabei wird die Datenanfrage nach assignee-email und owner-email gemacht. Der Owner ist derjenige, der den Kommentar erstellt, der Assignee derjenige der den Kommentar erhält.
Da in den Step Entries für die Projekt NUR der Projektleiter als Owner eingetragen ist, wurde dann kein Step Entry gefunden und es konnte kein Kommentar abgelegt werden.

Fix:
Datenbankabfrage ändern, sodass nur auf die assignee-email geschaut wird und es egal ist wer den Kommentar erstellen möchte von ZEP aus.

**Comment by LeitnerMi** [comment]
Aus fachlicher Seite, soll es so sein, dass nicht nur der Projektleiter Kommentare erstellen kann. 
Aus technischer Sicht? Es gibt keine andere Möglichkeit, als wie den owner des StepEntry zu ignorieren, oder? Es fühlt sich falsch an :sweat_smile:   @Ollitod

**Comment by Ollitod** [comment]
Ich finde es sollten immer nur für diesen MA zuständige Personen Kommentare via ZEP Email erstellen können. Ohne den Check auf den Owner könnte man ja dann das Kommentar zu einem völlig beliebigen StepEntry des MA hinzufügen, was ja keinen Sinn macht oder? In welchem Kontext trat der Fehler auf? @WernerBruckmueller @LeitnerMi FYI

**Comment by LeitnerMi** [comment]
Beim Testen von 718 hab ich mir das angeschaut und es werden die Projekte eigentlich richtig geparsed. Ich alle durchprobiert mit der Regex und nichts gefunden. Beim Testen bin ich dann auf den "Fehler" gestoßen.

**Comment by WernerBruckmueller** [comment]
Kein kommentar funktioniert @Ollitod

**Comment by WernerBruckmueller** [comment]
test erfolgreich
