### ISSUE TITLE
MEGA Dashboard: Gildenlead und PL darstellen

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#721]
What is the current state?
- Info muss in Personio nachgesehen werden

What is the desired state?
- Im MEGA Dashboard soll der MA sehen, welchen PL und welchen Gilden dieser zugewiesen hat. (ggf ist ein Mapping auf den echten namen notwendig)
- Wenn in Persionio bei PL ein ungültiger Wert eingetragen ist (zB leer, "NA", ...), so wird "nicht vorhanden" dargestellt
- Wenn in Persionio bei GL ein ungültiger Wert eingetragen ist (zB leer, "NA", ...), so wird "nicht vorhanden" dargestellt
 
Screenshots
TODO Figma @ViktoriaWip 

Screenshot aus Personio:
![image](https://github.com/Gepardec/mega/assets/16414159/2e857966-05fa-4ad9-8c7f-ad261c79e6f1)

**Comment by WernerBruckmueller** [comment]
@tomeindl @sgartner03 bitte um überprüfung ob das durch die persionio schnittstelle unterstützt wird. backendseitig kann es dann schon umgesetzt werden.
https://developer.personio.de/reference/introduction

**Comment by tomeindl** [comment]
Wie würden wir an die API Keys kommen? "The Authentication endpoint accepts the Client ID and Secret (**found in your API Credentials page**) "
