### ISSUE TITLE
Make ZEP-Url configurable as property

### ISSUE THREAD

**Issue by WernerGepardec** [Gepardec/mega#74]
As a dev I want to configure which ZEP environment is set.

DoD
- In the Prod the Prod-ZEP URL is configured
- In the Test the Test-ZEP URL is configured
- The property is documented in the wiki

**Comment by mml-gepardec** [comment]
The ZEP url is already a property and supports profiles for different configurations (see: https://quarkus.io/guides/config#configuration-profiles).
So I guess this story is just about adding the Prod configuration and document it in wiki?!

**Comment by WernerGepardec** [comment]
@mbrandm please check it with @mml-gepardec

**Comment by mml-gepardec** [comment]
As discussed with @mbrandm:
Property is already available, updated Readme
