### ISSUE TITLE
Define specific roles for MEGA reminders

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#79]
As MEGA-Reminder-System I want to remind specific users.

DoD
- [x] Read all active ZEP-users. Send specific reminder to them.
- [x] Read all active ZEP-users which are PL. Send specific reminder to them.
- [x] Hardcode the OM-user into the properties. Send a specific reminder to them.
- [ ] Be sure that the Testsystem doesn't send reminders to all users!

**Comment by mml-gepardec** [comment]
Blocked by #81
