### ISSUE TITLE
Adapt mail properties for environments

### ISSUE THREAD

**Issue by mml-gepardec** [Gepardec/mega#81]
As developer of the MEGA project I want to avoid test-specific code/workflows in the productive code. In order not to annoy users of the system with emails from the test system the environments **TEST** and **DEV** should use the mailer mock instead sending real emails:
`quarkus.mailer.mock=true`

Furthermore the property *mega.mail.employees.notification* should not be used anymore and therefore be removed from all application.properties-files.

**DEV** and **TEST** environments should not send any mails at all whereas the **PROD** environments should always send the mails. A configuration to disable notifications *per user* could be implemented in a future story.

**Comment by mml-gepardec** [comment]
This user story should be merged with #79 to avoid any side-effects

**Comment by cchet** [comment]
Already done
