### ISSUE TITLE
Employee login

### ISSUE THREAD

**Issue by WernerBruckmueller** [Gepardec/mega#9]
Als Mitarbeiter möchte ich mich im Dashboard anmelden.

Akzeptanzkriterien:
 - Anmeldung über Google (Überprüfung gegen ZEP, dass es sich um einen gültigen MA handelt)
 - Text auf der Willkommensseite, nach der Anmeldung: "Willkommen {user}!"

**Comment by Ruhsi** [comment]
Die Überprüfung des gültigen Mitarbeiters muss mittels Vergleich der Google-Mail-Adresse und der in ZEP hinterlegten Mail-Adresse gemacht werden, da es in der ZEP-Api keine Login/Signin-Methode gibt.

**Comment by cchet** [comment]
Already done
